### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by mhqschen** [allanpk716/ChineseSubFinder#11]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.11.0

环境: docker

## 你遇到什么问题了？

无法运行

## 你的问题弄重现嘛？

能重现

## docker-compose配置：

version: "3"
services:
  chinesesubfinder:
    container_name: chinesesubfinder
    image: allanpk716/chinesesubfinder:latest
    volumes:
      - /share/CACHEDEV1_DATA/Container/chinesesubfinder:/config
      - /share/CACHEDEV1_DATA/Container/chinesesubfinder/log:/app/Logs
      - /share/CACHEDEV1_DATA/Multimedia:/data
    environment:
      - PUID=1000
      - PGID=0
      - TZ=Asia/Shanghai
    restart: unless-stopped

## 配置文件：

UseProxy: false
HttpProxy: http://127.0.0.1:10809
EveryTime: 12h
Threads: 1
SubTypePriority: 0
DebugMode: false
SaveMultiSub: true
MovieFolder: /data/Movie
SeriesFolder: /data/TV

## 出错的日志信息可以复制一些出来吗？

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] 01-envfile: executing... ,
[cont-init.d] 01-envfile: exited 0.,
[cont-init.d] 10-adduser: executing... ,
,
-------------------------------------,
          _         (),
         | |  ___   _    __,
         | | / __| | |  /  \ ,
         | | \__ \ | | | () |,
         |_| |___/ |_|  \__/,
,
,
Brought to you by linuxserver.io,
-------------------------------------,
,
To support LSIO projects visit:,
https://www.linuxserver.io/donate/,
-------------------------------------,
GID/UID,
-------------------------------------,
,
User uid:    1000,
User gid:    0,
-------------------------------------,
,
[cont-init.d] 10-adduser: exited 0.,
[cont-init.d] 30-config: executing... ,
[cont-init.d] 30-config: exited 0.,
[cont-init.d] 50-config: executing... ,
[cont-init.d] 50-config: exited 0.,
[cont-init.d] 90-custom-folders: executing... ,
[cont-init.d] 90-custom-folders: exited 0.,
[cont-init.d] 99-custom-scripts: executing... ,
[cont-init.d] 99-custom-scripts: exited 0.,
[cont-init.d] done.,
[services.d] starting services,
[services.d] done.,
[INFO]: 2021-07-14 13:46:22 - MovieFolder: /data/Movie,
[INFO]: 2021-07-14 13:46:22 - SeriesFolder: /data/TV,
Download: https://npm.taobao.org/mirrors/chromium-browser-snapshots/Linux_x64/856583/chrome-linux.zip,
Progress: 00% 15% 25% 36% 44% 55% 65% 74% 83% 93% 100%,
Unzip to: /root/.cache/rod/chromium-856583,
Progress: 00% 16% 34% 47% 58% 69% 93% 100%,
,
[INFO]: 2021-07-14 13:46:40 - First Time Download Start,
[INFO]: 2021-07-14 13:46:40 - Download One Started...,
[INFO]: 2021-07-14 13:46:40 - Download One End...,
panic: runtime error: invalid memory address or nil pointer dereference,
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x95c4f7],
,
goroutine 1 [running]:,
github.com/allanpk716/ChineseSubFinder/emby_helper.(*EmbyHelper).RefreshEmbySubList(0x0, 0x7edae5, 0xc0001525f0, 0xb356e0),
	/homelab/buildspace/emby_helper/embyhelper.go:95 +0x37,
main.Downloader.RefreshEmbySubList(0x0, 0x0, 0x0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...),
	/homelab/buildspace/downloader.go:101 +0x79,
main.DownLoadStart(0x0, 0x0),
	/homelab/buildspace/main.go:101 +0x21f,
main.main(),
	/homelab/buildspace/main.go:71 +0x765,
[INFO]: 2021-07-14 13:46:40 - MovieFolder: /data/Movie,
[INFO]: 2021-07-14 13:46:40 - SeriesFolder: /data/TV

**Comment by wyc2896** [comment]
Same issue
date | stream | content
-- | -- | --
2021-07-14 06:51:26 | stdout | goroutine 1 [running]:
2021-07-14 06:51:26 | stdout |  
2021-07-14 06:51:26 | stdout | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x95c4f7]
2021-07-14 06:51:26 | stdout | panic: runtime error: invalid memory address or nil pointer dereference
2021-07-14 06:51:26 | stdout | [INFO]: 2021-07-14 14:51:26 - Download One End...
2021-07-14 06:51:26 | stdout | [INFO]: 2021-07-14 14:51:26 - Download One Started...
2021-07-14 06:51:26 | stdout | [INFO]: 2021-07-14 14:51:26 - First Time Download Start
2021-07-14 06:51:23 | stdout | [INFO]: 2021-07-14 14:51:23 - SeriesFolder: /media/Shows
2021-07-14 06:51:23 | stdout | [INFO]: 2021-07-14 14:51:23 - MovieFolder: /media/Movies
2021-07-14 06:51:23 | stdout | /homelab/buildspace/main.go:71 +0x765
2021-07-14 06:51:23 | stdout | main.main()
2021-07-14 06:51:23 | stdout | /homelab/buildspace/main.go:101 +0x21f
2021-07-14 06:51:23 | stdout | main.DownLoadStart(0x0, 0x0)
2021-07-14 06:51:23 | stdout | /homelab/buildspace/downloader.go:101 +0x79
2021-07-14 06:51:23 | stdout | main.Downloader.RefreshEmbySubList(0x0, 0x0, 0x0, 0x1, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2021-07-14 06:51:23 | stdout | /homelab/buildspace/emby_helper/embyhelper.go:95 +0x37
2021-07-14 06:51:23 | stdout | github.com/allanpk716/ChineseSubFinder/emby_helper.(*EmbyHelper).RefreshEmbySubList(0x0, 0x7edae5, 0xc0004a2190, 0xb356e0)

**Comment by allanpk716** [comment]
收到，正在推送更新。眼花没有覆盖到 nil 判断。同时在我这边居然没出错··· 

v0.11.1 修复，等待自动编译发布。

**Comment by mhqschen** [comment]
多谢修复~
