### ISSUE TITLE
v0.19.5 windows好像无法读取配置文件

### ISSUE THREAD

**Issue by SydraGITHUB** [allanpk716/ChineseSubFinder#157]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.19.5

环境: windows server 2022

## 你遇到什么问题了？

开启的时候闪退，看cmd信息好像是读不到配置文件

```
C:\Programs\Chinese_Sub_Finder_v0.19.5_Portable>chinesesubfinder.exe
panic: GetConfig - initConfigure error reading config:Config File "config" Not Found in "[]"

goroutine 1 [running]:
`github.com/allanpk716/ChineseSubFinder/internal/pkg/config.GetConfig.func1()`
        /home/runner/work/ChineseSubFinder/ChineseSubFinder/internal/pkg/config/config.go:20 +0x1fe
sync.(*Once).doSlow(0x3d762a, 0xc28320)
        /opt/hostedtoolcache/go/1.17.5/x64/src/sync/once.go:68 +0xd2
sync.(*Once).Do(...)
        /opt/hostedtoolcache/go/1.17.5/x64/src/sync/once.go:59
github.com/allanpk716/ChineseSubFinder/internal/pkg/config.GetConfig()
        /home/runner/work/ChineseSubFinder/ChineseSubFinder/internal/pkg/config/config.go:17 +0x31
github.com/allanpk716/ChineseSubFinder/internal/pkg/log_helper.GetLogger.func1()
        /home/runner/work/ChineseSubFinder/ChineseSubFinder/internal/pkg/log_helper/loghelper.go:49 +0x19
sync.(*Once).doSlow(0x64, 0xc00004be50)
        /opt/hostedtoolcache/go/1.17.5/x64/src/sync/once.go:68 +0xd2
sync.(*Once).Do(...)
        /opt/hostedtoolcache/go/1.17.5/x64/src/sync/once.go:59
github.com/allanpk716/ChineseSubFinder/internal/pkg/log_helper.GetLogger()
        /home/runner/work/ChineseSubFinder/ChineseSubFinder/internal/pkg/log_helper/loghelper.go:46 +0x31
main.init.0()
        /home/runner/work/ChineseSubFinder/ChineseSubFinder/cmd/chinesesubfinder/main.go:21 +0x1d
```

## 你的问题弄重现嘛？

能

##日志

没有生成日志文件

**Comment by allanpk716** [comment]
正在推送 v0.19.6，之前合并代码没有注意验证。
