### ISSUE TITLE
启动扫描以后出现 fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by guoyaobit** [allanpk716/ChineseSubFinder#192]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.20.3

环境:  来自dockerhub

## 你遇到什么问题了？

描述一下你遇到的问题
每次点立即启动以后都出现段错误

## 你的问题弄重现嘛？

每次都能重现

## 你期望的结果

描述以下你期望的结果

## 可以提供遇到问题时候，电影、连续剧的信息吗？

如下填写

视频的目录: X:\连续剧\杀死伊芙 (2018)

视频的信息: 杀死伊芙 - S01E01 - 姣好面容.mp4
目录设置的是空文件夹
![图片](https://user-images.githubusercontent.com/23020748/153159764-35d2fff0-fe6e-4ebf-93b9-49b3ff2a0bca.png)

## 出错的日志信息可以复制一些出来吗？

日志在程序的 Logs 目录下，如果你用的是 docker ，那么需要你映射出来。

> /volume1/docker/chinesesubfinder/logs:/app/Logs
[GIN] 2022/02/09 - 16:53:24 | 401 |     162.804µs |     192.168.5.1 | GET      "/v1/jobs/status"
[WARNING]: 2022-02-09 16:53:24 - DownFile.GetFileName is string.empty https://cdn.jsdelivr.net/gh/allanpk716/SomeThingsStatic/c31ViaG5Q.txt
[INFO]: 2022-02-09 16:53:24 - GetCode 2022-02-08 921684
[INFO]: 2022-02-09 16:53:24 - UseHttpProxy = false
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x63 pc=0x7fb4082ea448]

runtime stack:
runtime.throw({0x11b2d1c, 0x7fb3fb7fd840})
	/usr/local/go/src/runtime/panic.go:1198 +0x71
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:719 +0x396

goroutine 50 [syscall]:
runtime.cgocall(0xdb1b90, 0xc00048d590)
	/usr/local/go/src/runtime/cgocall.go:156 +0x5c fp=0xc00048d568 sp=0xc00048d530 pc=0x405b5c
net._C2func_getaddrinfo(0xc000b2c6a0, 0x0, 0xc000b2b980, 0xc000118508)
	_cgo_gotypes.go:91 +0x56 fp=0xc00048d590 sp=0xc00048d568 pc=0x5c35b6
net.cgoLookupIPCNAME.func1({0xc000b2c6a0, 0x0, 0x0}, 0xc000b2c680, 0xc00048d650)
	/usr/local/go/src/net/cgo_unix.go:163 +0x9f fp=0xc00048d5e8 sp=0xc00048d590 pc=0x5c52ff
net.cgoLookupIPCNAME({0x11664ff, 0x3}, {0xc000b2c680, 0x5})
	/usr/local/go/src/net/cgo_unix.go:163 +0x16d fp=0xc00048d738 sp=0xc00048d5e8 pc=0x5c4b4d
net.cgoIPLookup(0x236f1f0, {0x11664ff, 0xc000b2c690}, {0xc000b2c680, 0xc0007102c0})
	/usr/local/go/src/net/cgo_unix.go:220 +0x3b fp=0xc00048d7a8 sp=0xc00048d738 pc=0x5c53bb
net.cgoLookupIP·dwrap·25()
	/usr/local/go/src/net/cgo_unix.go:230 +0x36 fp=0xc00048d7e0 sp=0xc00048d7a8 pc=0x5c5836
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00048d7e8 sp=0xc00048d7e0 pc=0x467181
created by net.cgoLookupIP
	/usr/local/go/src/net/cgo_unix.go:230 +0x125

goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0x7fb40872af58, 0x72)
	/usr/local/go/src/runtime/netpoll.go:234 +0x89
internal/poll.(*pollDesc).wait(0xc0003a2500, 0xc000042800, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc0003a2500)
	/usr/local/go/src/internal/poll/fd_unix.go:402 +0x22c
net.(*netFD).accept(0xc0003a2500)
	/usr/local/go/src/net/fd_unix.go:173 +0x35
net.(*TCPListener).accept(0xc00000f8a8)
	/usr/local/go/src/net/tcpsock_posix.go:140 +0x28
net.(*TCPListener).Accept(0xc00000f8a8)
	/usr/local/go/src/net/tcpsock.go:262 +0x3d
net/http.(*Server).Serve(0xc000034460, {0x164d110, 0xc00000f8a8})
	/usr/local/go/src/net/http/server.go:3002 +0x394
net/http.(*Server).ListenAndServe(0xc000034460)
	/usr/local/go/src/net/http/server.go:2931 +0x7d
net/http.ListenAndServe(...)
	/usr/local/go/src/net/http/server.go:3185
github.com/gin-gonic/gin.(*Engine).Run(0xc000417380, {0xc00079fe70, 0x1, 0x1})
	/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/gin.go:356 +0x1d8
github.com/allanpk716/ChineseSubFinder/internal/backend.StartBackEnd(0xc000388460, 0x4)
	/homelab/buildspace/internal/backend/backend.go:38 +0x325
main.main()
	/homelab/buildspace/cmd/chinesesubfinder/main.go:51 +0x194

goroutine 8 [chan receive]:
github.com/panjf2000/ants/v2.(*Pool).purgePeriodically(0xc00045c0e0)
	/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.5/pool.go:69 +0x8b
created by github.com/panjf2000/ants/v2.NewPool
	/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.5/pool.go:137 +0x31b

goroutine 9 [select]:
net/http.(*Transport).getConn(0x1d92800, 0xc000b6e480, {{}, 0x0, {0x118f600, 0x5}, {0xc000b2c680, 0xd}, 0x0})
	/usr/local/go/src/net/http/transport.go:1372 +0x5d2
net/http.(*Transport).roundTrip(0x1d92800, 0xc0001d2400)
	/usr/local/go/src/net/http/transport.go:581 +0x774
net/http.(*Transport).RoundTrip(0xc0001d2400, 0x163f480)
	/usr/local/go/src/net/http/roundtrip.go:18 +0x19
net/http.send(0xc0001d2300, {0x163f480, 0x1d92800}, {0x113c4a0, 0x4c5f01, 0x2370680})
	/usr/local/go/src/net/http/client.go:252 +0x5d8
net/http.(*Client).send(0xc000b2b710, 0xc0001d2300, {0xc0001d2300, 0x2f, 0x2370680})
	/usr/local/go/src/net/http/client.go:176 +0x9b
net/http.(*Client).do(0xc000b2b710, 0xc0001d2300)
	/usr/local/go/src/net/http/client.go:725 +0x908
net/http.(*Client).Do(...)
	/usr/local/go/src/net/http/client.go:593
net/http.(*Client).Get(0x30, {0x118f600, 0xc000b2b6e0})
	/usr/local/go/src/net/http/client.go:480 +0x6a
github.com/allanpk716/ChineseSubFinder/internal/pkg/url_connectedness_helper.UrlConnectednessTest({0x118f600, 0x11}, {0x0, 0x1})
	/homelab/buildspace/internal/pkg/url_connectedness_helper/url_connectedness_helper.go:47 +0x249
github.com/allanpk716/ChineseSubFinder/internal/logic/pre_download_process.(*PreDownloadProcess).Check(0xc000b61de0)
	/homelab/buildspace/internal/logic/pre_download_process/pre_download_proces.go:108 +0x374
github.com/allanpk716/ChineseSubFinder/internal/logic/cron_helper.(*CronHelper).coreSubDownloadProcess(0xc0004a6c30)
	/homelab/buildspace/internal/logic/cron_helper/cron_helper.go:149 +0xf3
github.com/allanpk716/ChineseSubFinder/internal/logic/cron_helper.(*CronHelper).Start(0xc0004a6c30, 0x1)
	/homelab/buildspace/internal/logic/cron_helper/cron_helper.go:47 +0xf6
main.main.func1()
	/homelab/buildspace/cmd/chinesesubfinder/main.go:43 +0x85
created by main.main
	/homelab/buildspace/cmd/chinesesubfinder/main.go:41 +0xef

goroutine 15 [select]:
net.(*Resolver).lookupIPAddr(0x236f1e0, {0x16545f0, 0xc000b33200}, {0x11664ff, 0xc000077690}, {0xc000b2c680, 0x9})
	/usr/local/go/src/net/lookup.go:302 +0x5c7
net.(*Resolver).internetAddrList(0x16545f0, {0x16545f0, 0xc000b33200}, {0x11664ff, 0x3}, {0xc000b2c680, 0xd})
	/usr/local/go/src/net/ipsock.go:288 +0x67a
net.(*Resolver).resolveAddrList(0x23ad7b8, {0x16545f0, 0xc000b33200}, {0x1167d9d, 0x4}, {0x11664ff, 0xc000459960}, {0xc000b2c680, 0xd}, {0x0, ...})
	/usr/local/go/src/net/dial.go:221 +0x41b
net.(*Dialer).DialContext(0xc00003e2a0, {0x16545f0, 0xc000b33200}, {0x11664ff, 0x7fb408fd3310}, {0xc000b2c680, 0x118})
	/usr/local/go/src/net/dial.go:406 +0x448
net/http.(*Transport).dial(0xc000b33200, {0x16545f0, 0xc000b33200}, {0x11664ff, 0x0}, {0xc000b2c680, 0x0})
	/usr/local/go/src/net/http/transport.go:1166 +0xda
net/http.(*Transport).dialConn(0x1d92800, {0x16545f0, 0xc000b33200}, {{}, 0x0, {0x118f600, 0x5}, {0xc000b2c680, 0xd}, 0x0})
	/usr/local/go/src/net/http/transport.go:1604 +0x845
net/http.(*Transport).dialConnFor(0x14, 0xc0007102c0)
	/usr/local/go/src/net/http/transport.go:1446 +0xb0
created by net/http.(*Transport).queueForDial
	/usr/local/go/src/net/http/transport.go:1415 +0x3d7

goroutine 16 [select]:
net.cgoLookupIP({0x1654580, 0xc000b6e500}, {0x11664ff, 0x9}, {0xc000b2c680, 0xc00083c300})
	/usr/local/go/src/net/cgo_unix.go:231 +0x1b7
net.(*Resolver).lookupIP(0x236f1e0, {0x1654580, 0xc000b6e500}, {0x11664ff, 0x3}, {0xc000b2c680, 0x9})
	/usr/local/go/src/net/lookup_unix.go:97 +0x128
net.glob..func1({0x1654580, 0xc000b6e500}, 0x0, {0x11664ff, 0x0}, {0xc000b2c680, 0x6ba1d0})
	/usr/local/go/src/net/hook.go:23 +0x3d
net.(*Resolver).lookupIPAddr.func1()
	/usr/local/go/src/net/lookup.go:296 +0x9f
internal/singleflight.(*Group).doCall(0x236f1f0, 0xc000b722d0, {0xc000b2c690, 0xd}, 0xc0007102c0)
	/usr/local/go/src/internal/singleflight/singleflight.go:95 +0x3b
created by internal/singleflight.(*Group).DoChan
	/usr/local/go/src/internal/singleflight/singleflight.go:88 +0x2f1

goroutine 28 [IO wait]:
internal/poll.runtime_pollWait(0x7fb40872ad88, 0x72)
	/usr/local/go/src/runtime/netpoll.go:234 +0x89
internal/poll.(*pollDesc).wait(0xc0003a2000, 0xc00086c000, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc0003a2000, {0xc00086c000, 0x1000, 0x1000})
	/usr/local/go/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc0003a2000, {0xc00086c000, 0x1000001187ade, 0xc})
	/usr/local/go/src/net/fd_posix.go:56 +0x29
net.(*conn).Read(0xc000122000, {0xc00086c000, 0x1f, 0xc00085e0c8})
	/usr/local/go/src/net/net.go:183 +0x45
net/http.(*connReader).Read(0xc00085e0c0, {0xc00086c000, 0x1000, 0x1000})
	/usr/local/go/src/net/http/server.go:780 +0x16d
bufio.(*Reader).fill(0xc00086a000)
	/usr/local/go/src/bufio/bufio.go:101 +0x103
bufio.(*Reader).ReadSlice(0xc00086a000, 0x0)
	/usr/local/go/src/bufio/bufio.go:360 +0x2f
bufio.(*Reader).ReadLine(0xc00086a000)
	/usr/local/go/src/bufio/bufio.go:389 +0x27
net/textproto.(*Reader).readLineSlice(0xc00085e0f0)
	/usr/local/go/src/net/textproto/reader.go:57 +0x99
net/textproto.(*Reader).ReadLine(...)
	/usr/local/go/src/net/textproto/reader.go:38
net/http.readRequest(0xc000122000)
	/usr/local/go/src/net/http/request.go:1029 +0x79
net/http.(*conn).readRequest(0xc000860000, {0x1654580, 0xc000866000})
	/usr/local/go/src/net/http/server.go:966 +0x225
net/http.(*conn).serve(0xc000860000, {0x1654628, 0xc0004a7b60})
	/usr/local/go/src/net/http/server.go:1856 +0x865
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3034 +0x4e8

goroutine 13 [IO wait]:
internal/poll.runtime_pollWait(0x7fb40872ae70, 0x72)
	/usr/local/go/src/runtime/netpoll.go:234 +0x89
internal/poll.(*pollDesc).wait(0xc000770680, 0xc000133000, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc000770680, {0xc000133000, 0xf57, 0xf57})
	/usr/local/go/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc000770680, {0xc000133000, 0xc00013326c, 0x1a})
	/usr/local/go/src/net/fd_posix.go:56 +0x29
net.(*conn).Read(0xc000122a98, {0xc000133000, 0x400, 0xc00070f7f8})
	/usr/local/go/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc000b092d8, {0xc000133000, 0x0, 0x40c58d})
	/usr/local/go/src/crypto/tls/conn.go:777 +0x3d
bytes.(*Buffer).ReadFrom(0xc000411778, {0x163dd80, 0xc000b092d8})
	/usr/local/go/src/bytes/buffer.go:204 +0x98
crypto/tls.(*Conn).readFromUntil(0xc000411500, {0x163f3c0, 0xc000122a98}, 0xcf0)
	/usr/local/go/src/crypto/tls/conn.go:799 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc000411500, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:606 +0x112
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:574
crypto/tls.(*Conn).Read(0xc000411500, {0xc000b3a000, 0x1000, 0xc000488b60})
	/usr/local/go/src/crypto/tls/conn.go:1277 +0x16f
bufio.(*Reader).Read(0xc000b32de0, {0xc000b01b58, 0x9, 0xc000722540})
	/usr/local/go/src/bufio/bufio.go:227 +0x1b4
io.ReadAtLeast({0x163dba0, 0xc000b32de0}, {0xc000b01b58, 0x9, 0x9}, 0x9)
	/usr/local/go/src/io/io.go:328 +0x9a
io.ReadFull(...)
	/usr/local/go/src/io/io.go:347
net/http.http2readFrameHeader({0xc000b01b58, 0x9, 0xc000b2b380}, {0x163dba0, 0xc000b32de0})
	/usr/local/go/src/net/http/h2_bundle.go:1555 +0x6e
net/http.(*http2Framer).ReadFrame(0xc000b01b20)
	/usr/local/go/src/net/http/h2_bundle.go:1813 +0x95
net/http.(*http2clientConnReadLoop).run(0xc00070ff98)
	/usr/local/go/src/net/http/h2_bundle.go:8608 +0x130
net/http.(*http2ClientConn).readLoop(0xc00083c300)
	/usr/local/go/src/net/http/h2_bundle.go:8531 +0x6f
created by net/http.(*http2Transport).newClientConn
	/usr/local/go/src/net/http/h2_bundle.go:7325 +0xb85

goroutine 30 [IO wait]:
internal/poll.runtime_pollWait(0x7fb40872aca0, 0x72)
	/usr/local/go/src/runtime/netpoll.go:234 +0x89
internal/poll.(*pollDesc).wait(0xc0003a2180, 0xc000b8e000, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc0003a2180, {0xc000b8e000, 0x1000, 0x1000})
	/usr/local/go/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc0003a2180, {0xc000b8e000, 0xc000868040, 0xc0006996b0})
	/usr/local/go/src/net/fd_posix.go:56 +0x29
net.(*conn).Read(0xc000122038, {0xc000b8e000, 0x24, 0xc00085e398})
	/usr/local/go/src/net/net.go:183 +0x45
net/http.(*connReader).Read(0xc00085e390, {0xc000b8e000, 0x1000, 0x1000})
	/usr/local/go/src/net/http/server.go:780 +0x16d
bufio.(*Reader).fill(0xc00086a120)
	/usr/local/go/src/bufio/bufio.go:101 +0x103
bufio.(*Reader).ReadSlice(0xc00086a120, 0x0)
	/usr/local/go/src/bufio/bufio.go:360 +0x2f
bufio.(*Reader).ReadLine(0xc00086a120)
	/usr/local/go/src/bufio/bufio.go:389 +0x27
net/textproto.(*Reader).readLineSlice(0xc00085e3c0)
	/usr/local/go/src/net/textproto/reader.go:57 +0x99
net/textproto.(*Reader).ReadLine(...)
	/usr/local/go/src/net/textproto/reader.go:38
net/http.readRequest(0xc000122038)
	/usr/local/go/src/net/http/request.go:1029 +0x79
net/http.(*conn).readRequest(0xc0008600a0, {0x1654580, 0xc000866180})
	/usr/local/go/src/net/http/server.go:966 +0x225
net/http.(*conn).serve(0xc0008600a0, {0x1654628, 0xc0004a7b60})
	/usr/local/go/src/net/http/server.go:1856 +0x865
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3034 +0x4e8

**Comment by allanpk716** [comment]
我不理解为何在这里无法正确的捕捉异常

```
github.com/allanpk716/ChineseSubFinder/internal/pkg/url_connectedness_helper.UrlConnectednessTest({0x118f600, 0x11}, {0x0, 0x1})
/homelab/buildspace/internal/pkg/url_connectedness_helper/url_connectedness_helper.go:47 +0x249
```

需要其他人帮看看才行
