### ISSUE TITLE
ubuntu server 下一直反复重启

### ISSUE THREAD

**Issue by xiongking** [allanpk716/ChineseSubFinder#288]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本:  v0.24.1
>
> 环境: ubuntu server21.10 ，docker 
>

## 你遇到什么问题了？

> 报错反复重启
>(EE) 
>Fatal server error:
>(EE) Server is already active for display 99
>	If this server is no longer running, remove /tmp/.X99-lock
>	and start again.
>(EE) 

## 你的问题弄重现嘛？

> v.2x无论什么版本都能够重新

## 你期望的结果

> 

## 给出当前程序的配置文件

```json
{
    "user_info":{
        "username":"****",
        "password":"****"
    },
    "common_settings":{
        "scan_interval":"6h",
        "threads":1,
        "run_scan_at_start_up":true,
        "movie_paths":[
            "/media/movie"
        ],
        "series_paths":[
            "/media/tv"
        ]
    },
    "advanced_settings":{
        "proxy_settings":{
            "use_http_proxy":false,
            "http_proxy_address":""
        },
        "debug_mode":false,
        "save_full_season_tmp_subtitles":false,
        "sub_type_priority":0,
        "sub_name_formatter":0,
        "save_multi_sub":false,
        "custom_video_exts":[

        ],
        "fix_time_line":false,
        "topic":1
    },
    "emby_settings":{
        "enable":true,
        "address_url":"http://******8096",
        "api_key":"*****",
        "max_request_video_number":3000,
        "skip_watched":false,
        "movie_paths_mapping":{
            "/media/movie":"/downloads/link/movie"
        },
        "series_paths_mapping":{
            "/media/tv":"/downloads/link/tv"
        }
    },
    "developer_settings":{
        "enable":false,
        "bark_server_address":""
    },
    "timeline_fixer_settings":{
        "max_offset_time":120,
        "min_offset":0.1
    },
    "experimental_function":{
        "auto_change_sub_encode":{
            "enable":false,
            "des_encode_type":0
        },
        "chs_cht_changer":{
            "enable":false,
            "des_chinese_language_type":0
        },
        "remote_chrome_settings":{
            "enable":false,
            "remote_docker_url":"",
            "remote_adblock_path":"",
            "remote_user_data_dir":""
        }
    }
}
```

## 如果是使用 Docker，请给出对应的配置信息

> 
```
##################################################
version: "3.8"
networks:
  default:
    driver: bridge



services:
##################################################
# All services / apps go below this line

  chinesesubfinder:
    container_name: chinesesubfinder
    image: allanpk716/chinesesubfinder:v0.24.1
    restart: unless-stopped
    networks:
      - default
    ports:
      - "19035:19035"
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - ${DOCKERDIR}/chinesesubfinder/config:/config
      - ${DOCKERDIR}/chinesesubfinder/cache:/app/cache
      - /downloads/link:/media
    ```

## 请给出当次问题的完整日志

> 日志在程序的 Logs 目录下，如果你用的是 docker ，那么需要你映射出来。

> /volume1/docker/chinesesubfinder/config:/config 下，Logs 中
```
[INFO]: 2022-04-04 23:12:27 - PreDownloadProcess.Init() End
[INFO]: 2022-04-04 23:12:27 - PreDownloadProcess.Check() Start...
[INFO]: 2022-04-04 23:12:27 - UseHttpProxy = false
[INFO]: 2022-04-04 23:12:27 - ConfigRootDirFPath /config/Logs
[INFO]: 2022-04-04 23:12:27 - matches logs: 21
[INFO]: 2022-04-04 23:12:27 - ChineseSubFinder Version: v0.24.1
[INFO]: 2022-04-04 23:12:27 - WebUI will listen at 0.0.0.0:19035
[INFO]: 2022-04-04 23:12:27 - Try Start Server At Port 19035
[INFO]: 2022-04-04 23:12:27 - Setup is Done
[INFO]: 2022-04-04 23:12:27 - First Time coreSubDownloadProcess Start
[INFO]: 2022-04-04 23:12:27 - Reload Log Settings, level = Info
[INFO]: 2022-04-04 23:12:27 - ConfigRootDirFPath /config/Logs
[INFO]: 2022-04-04 23:12:27 - matches logs: 20
[INFO]: 2022-04-04 23:12:27 - OneTimeSubtitleScanStart
[INFO]: 2022-04-04 23:12:27 - PreDownloadProcess.Init() Start...
[WARNING]: 2022-04-04 23:12:44 - DownFile.GetFileName is string.empty https://cdn.jsdelivr.net/gh/allanpk716/SomeThingsStatic/202244c31ViaG5Q.txt
[INFO]: 2022-04-04 23:12:44 - GetCode 2022-04-04 951275
[INFO]: 2022-04-04 23:12:44 - ClearRodTmpRootFolder Done
[INFO]: 2022-04-04 23:12:44 - PreDownloadProcess.Init() End
[INFO]: 2022-04-04 23:12:44 - PreDownloadProcess.Check() Start...
[INFO]: 2022-04-04 23:12:44 - UseHttpProxy = false
[INFO]: 2022-04-04 23:12:44 - ConfigRootDirFPath /config/Logs
[INFO]: 2022-04-04 23:12:44 - matches logs: 21
[INFO]: 2022-04-04 23:12:44 - ChineseSubFinder Version: v0.24.1
[INFO]: 2022-04-04 23:12:44 - WebUI will listen at 0.0.0.0:19035
[INFO]: 2022-04-04 23:12:44 - Setup is Done
[INFO]: 2022-04-04 23:12:44 - First Time coreSubDownloadProcess Start
[INFO]: 2022-04-04 23:12:44 - Try Start Server At Port 19035
[INFO]: 2022-04-04 23:12:44 - Reload Log Settings, level = Info
[INFO]: 2022-04-04 23:12:44 - ConfigRootDirFPath /config/Logs
[INFO]: 2022-04-04 23:12:44 - matches logs: 20
[INFO]: 2022-04-04 23:12:44 - OneTimeSubtitleScanStart
[INFO]: 2022-04-04 23:12:44 - PreDownloadProcess.Init() Start...
[WARNING]: 2022-04-04 23:12:55 - DownFile.GetFileName is string.empty https://cdn.jsdelivr.net/gh/allanpk716/SomeThingsStatic/202244c31ViaG5Q.txt
[INFO]: 2022-04-04 23:12:55 - GetCode 2022-04-04 951275
[INFO]: 2022-04-04 23:12:55 - ClearRodTmpRootFolder Done
[INFO]: 2022-04-04 23:12:55 - PreDownloadProcess.Init() End
[INFO]: 2022-04-04 23:12:55 - PreDownloadProcess.Check() Start...
[INFO]: 2022-04-04 23:12:55 - UseHttpProxy = false
[INFO]: 2022-04-04 23:12:55 - ConfigRootDirFPath /config/Logs
[INFO]: 2022-04-04 23:12:55 - matches logs: 21
[INFO]: 2022-04-04 23:12:55 - ChineseSubFinder Version: v0.24.1
[INFO]: 2022-04-04 23:12:55 - WebUI will listen at 0.0.0.0:19035
[INFO]: 2022-04-04 23:12:55 - Try Start Server At Port 19035
[INFO]: 2022-04-04 23:12:55 - Setup is Done
[INFO]: 2022-04-04 23:12:55 - First Time coreSubDownloadProcess Start
[INFO]: 2022-04-04 23:12:55 - Reload Log Settings, level = Info
[INFO]: 2022-04-04 23:12:55 - ConfigRootDirFPath /config/Logs
[INFO]: 2022-04-04 23:12:55 - matches logs: 20
[INFO]: 2022-04-04 23:12:55 - OneTimeSubtitleScanStart
[INFO]: 2022-04-04 23:12:55 - PreDownloadProcess.Init() Start...
```

> portainer 的log中报错
```

goroutine 5 [select]:
net/http.(*Transport).getConn(0x1df29c0, 0xc000076300, {{}, 0x0, {0x11b0652, 0x5}, {0xc000254eb0, 0xd}, 0x0})
	/usr/local/go/src/net/http/transport.go:1372 +0x5d2
net/http.(*Transport).roundTrip(0x1df29c0, 0xc0005c7100)
	/usr/local/go/src/net/http/transport.go:581 +0x774
net/http.(*Transport).RoundTrip(0xc0005c7100, 0x168cf40)
	/usr/local/go/src/net/http/roundtrip.go:18 +0x19
net/http.send(0xc0005c7000, {0x168cf40, 0x1df29c0}, {0x115cbc0, 0x4c5f01, 0x23d1940})
	/usr/local/go/src/net/http/client.go:252 +0x5d8
net/http.(*Client).send(0xc0001e2a80, 0xc0005c7000, {0xc0005c7000, 0x2f, 0x23d1940})
	/usr/local/go/src/net/http/client.go:176 +0x9b
net/http.(*Client).do(0xc0001e2a80, 0xc0005c7000)
	/usr/local/go/src/net/http/client.go:725 +0x908
net/http.(*Client).Do(...)
	/usr/local/go/src/net/http/client.go:593
net/http.(*Client).Get(0x30, {0x11b0652, 0xc0001e2a50})
	/usr/local/go/src/net/http/client.go:480 +0x6a
github.com/allanpk716/ChineseSubFinder/internal/pkg/url_connectedness_helper.UrlConnectednessTest({0x11b0652, 0x11}, {0x0, 0x1})
	/homelab/buildspace/internal/pkg/url_connectedness_helper/url_connectedness_helper.go:47 +0x249
github.com/allanpk716/ChineseSubFinder/internal/logic/pre_download_process.(*PreDownloadProcess).Check(0xc00048dd20)
	/homelab/buildspace/internal/logic/pre_download_process/pre_download_proces.go:129 +0x43b
github.com/allanpk716/ChineseSubFinder/internal/logic/cron_helper.(*CronHelper).coreSubDownloadProcess(0xc00059f350)
	/homelab/buildspace/internal/logic/cron_helper/cron_helper.go:190 +0x37c
github.com/allanpk716/ChineseSubFinder/internal/logic/cron_helper.(*CronHelper).Start(0xc00059f350, 0x1)
	/homelab/buildspace/internal/logic/cron_helper/cron_helper.go:48 +0x385
main.main.func1()
	/homelab/buildspace/cmd/chinesesubfinder/main.go:38 +0x85
created by main.main
	/homelab/buildspace/cmd/chinesesubfinder/main.go:36 +0xef

goroutine 6 [select]:
github.com/allanpk716/ChineseSubFinder/internal/backend/ws_helper.(*Hub).Run(0xc00020bfe0)
	/homelab/buildspace/internal/backend/ws_helper/hub.go:30 +0xf5
created by github.com/allanpk716/ChineseSubFinder/internal/backend.StartBackEnd
	/homelab/buildspace/internal/backend/backend.go:42 +0x3a5

goroutine 13 [select]:
net.(*Resolver).lookupIPAddr(0x23d04a0, {0x16a24b0, 0xc0005b9a40}, {0x11873eb, 0x15cc}, {0xc000254eb0, 0x9})
	/usr/local/go/src/net/lookup.go:302 +0x5c7
net.(*Resolver).internetAddrList(0x16a24b0, {0x16a24b0, 0xc0005b9a40}, {0x11873eb, 0x3}, {0xc000254eb0, 0xd})
	/usr/local/go/src/net/ipsock.go:288 +0x67a
net.(*Resolver).resolveAddrList(0x240ecf0, {0x16a24b0, 0xc0005b9a40}, {0x1188c98, 0x4}, {0x11873eb, 0x0}, {0xc000254eb0, 0xd}, {0x0, ...})
	/usr/local/go/src/net/dial.go:221 +0x41b
net.(*Dialer).DialContext(0xc0000b21e0, {0x16a24b0, 0xc0005b9a40}, {0x11873eb, 0x7fb34a06bea8}, {0xc000254eb0, 0x118})
	/usr/local/go/src/net/dial.go:406 +0x448
net/http.(*Transport).dial(0xc0005b9a40, {0x16a24b0, 0xc0005b9a40}, {0x11873eb, 0x16a2478}, {0xc000254eb0, 0x1697be8})
	/usr/local/go/src/net/http/transport.go:1166 +0xda
net/http.(*Transport).dialConn(0x1df29c0, {0x16a24b0, 0xc0005b9a40}, {{}, 0x0, {0x11b0652, 0x5}, {0xc000254eb0, 0xd}, 0x0})
	/usr/local/go/src/net/http/transport.go:1604 +0x845
net/http.(*Transport).dialConnFor(0x14, 0xc0000e04d0)
	/usr/local/go/src/net/http/transport.go:1446 +0xb0
created by net/http.(*Transport).queueForDial
	/usr/local/go/src/net/http/transport.go:1415 +0x3d7

goroutine 14 [select]:
net.cgoLookupIP({0x16a2440, 0xc0003aef40}, {0x11873eb, 0x9}, {0xc000254eb0, 0xc0005cf200})
	/usr/local/go/src/net/cgo_unix.go:231 +0x1b7
net.(*Resolver).lookupIP(0x23d04a0, {0x16a2440, 0xc0003aef40}, {0x11873eb, 0x3}, {0xc000254eb0, 0x9})
	/usr/local/go/src/net/lookup_unix.go:97 +0x128
net.glob..func1({0x16a2440, 0xc0003aef40}, 0x0, {0x11873eb, 0x0}, {0xc000254eb0, 0x6bae90})
	/usr/local/go/src/net/hook.go:23 +0x3d
net.(*Resolver).lookupIPAddr.func1()
	/usr/local/go/src/net/lookup.go:296 +0x9f
internal/singleflight.(*Group).doCall(0x23d04b0, 0xc0004a01e0, {0xc000254ec0, 0xd}, 0xc0000e04d0)
	/usr/local/go/src/internal/singleflight/singleflight.go:95 +0x3b
created by internal/singleflight.(*Group).DoChan
	/usr/local/go/src/internal/singleflight/singleflight.go:88 +0x2f1

goroutine 11 [IO wait]:
internal/poll.runtime_pollWait(0x7fb321394eb0, 0x72)
	/usr/local/go/src/runtime/netpoll.go:234 +0x89
internal/poll.(*pollDesc).wait(0xc0005ca480, 0xc00011e800, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc0005ca480, {0xc00011e800, 0x15d1, 0x15d1})
	/usr/local/go/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc0005ca480, {0xc00011e800, 0x70000002a, 0x760000002b})
	/usr/local/go/src/net/fd_posix.go:56 +0x29
net.(*conn).Read(0xc000010978, {0xc00011e800, 0x0, 0xc0005bf7f8})
	/usr/local/go/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc00065f410, {0xc00011e800, 0x0, 0x40c58d})
	/usr/local/go/src/crypto/tls/conn.go:777 +0x3d
bytes.(*Buffer).ReadFrom(0xc0003a5778, {0x168b7a0, 0xc00065f410})
	/usr/local/go/src/bytes/buffer.go:204 +0x98
crypto/tls.(*Conn).readFromUntil(0xc0003a5500, {0x168ce80, 0xc000010978}, 0xc0005fa9a0)
	/usr/local/go/src/crypto/tls/conn.go:799 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc0003a5500, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:606 +0x112
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:574
crypto/tls.(*Conn).Read(0xc0003a5500, {0xc000145000, 0x1000, 0xc000001860})
	/usr/local/go/src/crypto/tls/conn.go:1277 +0x16f
bufio.(*Reader).Read(0xc0005b9380, {0xc00086d998, 0x9, 0xc0005d1920})
	/usr/local/go/src/bufio/bufio.go:227 +0x1b4
io.ReadAtLeast({0x168b5c0, 0xc0005b9380}, {0xc00086d998, 0x9, 0x9}, 0x9)
	/usr/local/go/src/io/io.go:328 +0x9a
io.ReadFull(...)
	/usr/local/go/src/io/io.go:347
net/http.http2readFrameHeader({0xc00086d998, 0x9, 0xc0001e2360}, {0x168b5c0, 0xc0005b9380})
	/usr/local/go/src/net/http/h2_bundle.go:1555 +0x6e
net/http.(*http2Framer).ReadFrame(0xc00086d960)
	/usr/local/go/src/net/http/h2_bundle.go:1813 +0x95
net/http.(*http2clientConnReadLoop).run(0xc0005bff98)
	/usr/local/go/src/net/http/h2_bundle.go:8608 +0x130
net/http.(*http2ClientConn).readLoop(0xc0005cf200)
	/usr/local/go/src/net/http/h2_bundle.go:8531 +0x6f
created by net/http.(*http2Transport).newClientConn
	/usr/local/go/src/net/http/h2_bundle.go:7325 +0xb85
(EE) 
Fatal server error:
(EE) Server is already active for display 99
	If this server is no longer running, remove /tmp/.X99-lock
	and start again.
(EE) 
[INFO]: 2022-04-04 23:04:49 - ConfigRootDirFPath /config/Logs
[INFO]: 2022-04-04 23:04:49 - matches logs: 21
[INFO]: 2022-04-04 23:04:49 - ChineseSubFinder Version: v0.24.1
[INFO]: 2022-04-04 23:04:49 - WebUI will listen at 0.0.0.0:19035
[INFO]: 2022-04-04 23:04:49 - Try Start Server At Port 19035
[INFO]: 2022-04-04 23:04:49 - Setup is Done
[INFO]: 2022-04-04 23:04:49 - First Time coreSubDownloadProcess Start
[INFO]: 2022-04-04 23:04:49 - Reload Log Settings, level = Info
[INFO]: 2022-04-04 23:04:49 - ConfigRootDirFPath /config/Logs
[INFO]: 2022-04-04 23:04:49 - matches logs: 20
[INFO]: 2022-04-04 23:04:49 - OneTimeSubtitleScanStart
[INFO]: 2022-04-04 23:04:49 - PreDownloadProcess.Init() Start...
```

**Comment by allanpk716** [comment]
谢谢反馈，我看了下代码，都做了异常处理了，为何还能崩溃不太理解。需要有人能协助帮看看为什么，之前看有些人也反馈不停的重启，估计也是一样的问题。

https://github.com/allanpk716/ChineseSubFinder/blob/e3f62bbef44bdceead2a27a7a28a07f641d9e2e4/internal/pkg/url_connectedness_helper/url_connectedness_helper.go#L47

**Comment by turygo** [comment]
同样有这个问题，环境是ubuntu server 20.04，subfinder运行在docker下，自从更新到v0.2以后就开始出现这个问题，现在只能停留在v0.19。请问可以怎么看具体哪里出问题了？要如何调试？

**Comment by allanpk716** [comment]
> 同样有这个问题，环境是ubuntu server 20.04，subfinder运行在docker下，自从更新到v0.2以后就开始出现这个问题，现在只能停留在v0.19。请问可以怎么看具体哪里出问题了？要如何调试？

升级最新，看 docker 日志。以及你的系统是否支持 chrome

**Comment by HernandoR** [comment]
same problem

**Comment by xiongking** [comment]
> > 同样有这个问题，环境是ubuntu server 20.04，subfinder运行在docker下，自从更新到v0.2以后就开始出现这个问题，现在只能停留在v0.19。请问可以怎么看具体哪里出问题了？要如何调试？
> 
> 升级最新，看 docker 日志。以及你的系统是否支持 chrome

server版，没有chrome.

**Comment by allanpk716** [comment]
原来如此。准备做分布式任务，后续客户端会有轻量级版本，只需要 http client 即可

**Comment by allanpk716** [comment]
已经推出 Lite 版本，试试。具体见首页的部署教程。
