### ISSUE TITLE
字幕下载时间BUG

### ISSUE THREAD

**Issue by millsguo** [allanpk716/ChineseSubFinder#339]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: v0.26.0
>
> 环境: docker
>
> 在程序运行日志头部或者 Web UI 可以看到
[INFO]: 2022-05-16 15:57:08 - Next Sub Scan Will Process At: 0001-01-01 00:00:00

## 你遇到什么问题了？

> 字幕扫描开始时间不对吧？等了好久都没有下载字幕

## 你的问题弄重现嘛？

> 能够重现

## 你期望的结果

> 正常下载字幕

**Comment by allanpk716** [comment]
1. 你现在选择的下载扫描逻辑是那个？
2. 是否有开关过“守护”进程，如果有的话，有一定几率出问题

**Comment by hanruochen1** [comment]
下载不了现在，我在的群组里，有好几个用的今天都下载不了字幕，一直卡在等待下载下载的状态

**Comment by lqx1981** [comment]
> 下载不了现在，我在的群组里，有好几个用的今天都下载不了字幕，一直卡在等待下载下载的状态

我也是，一直是在等待下载，没法下载

**Comment by allanpk716** [comment]
是 bug，群里反馈我定位到了，是逻辑问题。急着用就把这个先关闭。正在编译推送 v0.26.1

## 截图
![image](https://user-images.githubusercontent.com/1176000/168567043-a9682253-ecc1-4f35-b36e-6582d41ca81b.png)

**Comment by ihola777** [comment]
docker更新到0.26.2 开始任务后无法下载
```json
{
    "SpeedDevMode": false,
    "user_info": {
        "username": "xxx",
        "password": "xxxx"
    },
    "common_settings": {
        "interval_or_assign_or_custom": 0,
        "scan_interval": "@every 6h",
        "threads": 3,
        "run_scan_at_start_up": true,
        "movie_paths": [
            "/media/电影"
        ],
        "series_paths": [
            "/media/电视剧"
        ],
        "local_static_file_port": "19037"
    },
    "subtitle_sources": {
        "assrt_settings": {
            "token": ""
        }
    },
    "advanced_settings": {
        "proxy_settings": {
            "use_proxy": true,
            "use_which_proxy_protocol": "http",
            "local_http_proxy_server_port": "19036",
            "input_proxy_address": "xxxx",
            "input_proxy_port": "8118",
            "need_pwd": false,
            "input_proxy_username": "",
            "input_proxy_password": ""
        },
        "debug_mode": false,
        "save_full_season_tmp_subtitles": true,
        "sub_type_priority": 0,
        "sub_name_formatter": 0,
        "save_multi_sub": false,
        "custom_video_exts": [],
        "fix_time_line": true,
        "topic": 1,
        "suppliers_settings": {
            "xunlei": {
                "name": "xunlei",
                "root_url": "http://sub.xmp.sandai.net:8000/subxl/%s.json",
                "daily_download_limit": -1
            },
            "shooter": {
                "name": "shooter",
                "root_url": "https://www.shooter.cn/api/subapi.php",
                "daily_download_limit": -1
            },
            "subhd": {
                "name": "subhd",
                "root_url": "https://subhd.tv",
                "daily_download_limit": 20
            },
            "zimuku": {
                "name": "zimuku",
                "root_url": "https://zimuku.org",
                "daily_download_limit": 20
            },
            "assrt": {
                "name": "assrt",
                "root_url": "https://api.assrt.net/v1",
                "daily_download_limit": -1
            }
        },
        "scan_logic": {
            "skip_chinese_movie": true,
            "skip_chinese_series": true
        },
        "task_queue": {
            "max_retry_times": 3,
            "one_job_time_out": 300,
            "interval": 10,
            "expiration_time": 90,
            "download_sub_during_x_days": 7,
            "one_sub_download_interval": 12,
            "check_pulic_ip_target_site": ""
        },
        "download_file_cache": {
            "ttl": 4320,
            "unit": "hour"
        }
    },
    "emby_settings": {
        "enable": false,
        "address_url": "",
        "api_key": "",
        "max_request_video_number": 500,
        "skip_watched": false,
        "movie_paths_mapping": {
            "/media/电影": ""
        },
        "series_paths_mapping": {
            "/media/电视剧": ""
        },
        "auto_or_manual": false,
        "threads": 3
    },
    "developer_settings": {
        "enable": false,
        "bark_server_address": ""
    },
    "timeline_fixer_settings": {
        "max_offset_time": 120,
        "min_offset": 0.1
    },
    "experimental_function": {
        "auto_change_sub_encode": {
            "enable": false,
            "des_encode_type": 0
        },
        "chs_cht_changer": {
            "enable": false,
            "des_chinese_language_type": 0
        },
        "remote_chrome_settings": {
            "enable": false,
            "remote_docker_url": "",
            "remote_adblock_path": "",
            "remote_user_data_dir": ""
        },
        "api_key_settings": {
            "enabled": false,
            "key": ""
        },
        "local_chrome_settings": {
            "enabled": false,
            "local_chrome_exe_f_path": ""
        }
    }
}
```

```
[ERROR]: 2022-05-17 05:35:43 - Downloader.QueueDownloader() panic
[ERROR]: 2022-05-17 05:35:43 - goroutine 1674 [running]:
github.com/allanpk716/ChineseSubFinder/internal/pkg/my_util.PrintPanicStack(0xc00050c2a0)
	/homelab/buildspace/internal/pkg/my_util/util.go:852 +0x3d
github.com/allanpk716/ChineseSubFinder/internal/pkg/downloader.(*Downloader).QueueDownloader.func1()
	/homelab/buildspace/internal/pkg/downloader/downloader.go:176 +0x7c
panic({0x10c3280, 0x1ee99c0})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
github.com/allanpk716/ChineseSubFinder/internal/logic/emby_helper.(*EmbyHelper).IsVideoPlayed(0x0, {0x0, 0x0})
	/homelab/buildspace/internal/logic/emby_helper/embyhelper.go:317 +0x41
github.com/allanpk716/ChineseSubFinder/internal/pkg/downloader.(*Downloader).QueueDownloader(0xc0007f35f0)
	/homelab/buildspace/internal/pkg/downloader/downloader.go:202 +0x365
github.com/robfig/cron/v3.FuncJob.Run(0xc0007a1768)
	/go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/cron.go:131 +0x1a
github.com/robfig/cron/v3.SkipIfStillRunning.func1.1()
	/go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/chain.go:85 +0x63
github.com/robfig/cron/v3.FuncJob.Run(0xc0004f8140)
	/go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/cron.go:131 +0x1a
github.com/robfig/cron/v3.(*Cron).startJob.func1()
	/go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/cron.go:307 +0x6a
created by github.com/robfig/cron/v3.(*Cron).startJob
	/go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/cron.go:305 +0xb2

[ERROR]: 2022-05-17 05:35:58 - Downloader.QueueDownloader() panic
[ERROR]: 2022-05-17 05:35:58 - goroutine 1675 [running]:
github.com/allanpk716/ChineseSubFinder/internal/pkg/my_util.PrintPanicStack(0xc00050c2a0)
	/homelab/buildspace/internal/pkg/my_util/util.go:852 +0x3d
github.com/allanpk716/ChineseSubFinder/internal/pkg/downloader.(*Downloader).QueueDownloader.func1()
	/homelab/buildspace/internal/pkg/downloader/downloader.go:176 +0x7c
panic({0x10c3280, 0x1ee99c0})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
github.com/allanpk716/ChineseSubFinder/internal/logic/emby_helper.(*EmbyHelper).IsVideoPlayed(0x0, {0x0, 0x0})
	/homelab/buildspace/internal/logic/emby_helper/embyhelper.go:317 +0x41
github.com/allanpk716/ChineseSubFinder/internal/pkg/downloader.(*Downloader).QueueDownloader(0xc0007f35f0)
	/homelab/buildspace/internal/pkg/downloader/downloader.go:202 +0x365
github.com/robfig/cron/v3.FuncJob.Run(0xc0007a1768)
	/go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/cron.go:131 +0x1a
github.com/robfig/cron/v3.SkipIfStillRunning.func1.1()
	/go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/chain.go:85 +0x63
github.com/robfig/cron/v3.FuncJob.Run(0xc0004f8140)
	/go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/cron.go:131 +0x1a
github.com/robfig/cron/v3.(*Cron).startJob.func1()
	/go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/cron.go:307 +0x6a
created by github.com/robfig/cron/v3.(*Cron).startJob
	/go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/cron.go:305 +0xb2

[ERROR]: 2022-05-17 05:36:13 - Downloader.QueueDownloader() panic
[ERROR]: 2022-05-17 05:36:13 - goroutine 1677 [running]:
github.com/allanpk716/ChineseSubFinder/internal/pkg/my_util.PrintPanicStack(0xc00050c2a0)
	/homelab/buildspace/internal/pkg/my_util/util.go:852 +0x3d
github.com/allanpk716/ChineseSubFinder/internal/pkg/downloader.(*Downloader).QueueDownloader.func1()
	/homelab/buildspace/internal/pkg/downloader/downloader.go:176 +0x7c
panic({0x10c3280, 0x1ee99c0})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
github.com/allanpk716/ChineseSubFinder/internal/logic/emby_helper.(*EmbyHelper).IsVideoPlayed(0x0, {0x0, 0x0})
	/homelab/buildspace/internal/logic/emby_helper/embyhelper.go:317 +0x41
github.com/allanpk716/ChineseSubFinder/internal/pkg/downloader.(*Downloader).QueueDownloader(0xc0007f35f0)
	/homelab/buildspace/internal/pkg/downloader/downloader.go:202 +0x365
github.com/robfig/cron/v3.FuncJob.Run(0xc0007a1768)
	/go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/cron.go:131 +0x1a
github.com/robfig/cron/v3.SkipIfStillRunning.func1.1()
	/go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/chain.go:85 +0x63
github.com/robfig/cron/v3.FuncJob.Run(0xc0004f8230)
	/go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/cron.go:131 +0x1a
github.com/robfig/cron/v3.(*Cron).startJob.func1()
	/go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/cron.go:307 +0x6a
created by github.com/robfig/cron/v3.(*Cron).startJob
	/go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/cron.go:305 +0xb2
```

**Comment by allanpk716** [comment]
推送  v0.26.3  see #345 @ihola777  你们遇到的问题一样
