### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by boer0327** [allanpk716/ChineseSubFinder#375]
## 你使用的 chinesesubfinder 是什么版本，什么环境？
DSM docker
> chinesesubfinder 版本: vx.x.x
> v0.28.2
> 环境: docker or Window or Linux or MAC
> docker
> 在程序运行日志头部或者 Web UI 可以看到
Web UI 打不开， 碰到错误后不停的重复扫描
## 你遇到什么问题了？
不能正常运行
> 描述一下你遇到的问题
在0.27版本开始运行一段时间是没有问题的， 昨天突然发现字幕不下载了，发现web打不开，查看日志就发现这个panic错误，但是程序会不停的重复这个步骤。
## 你的问题弄重现嘛？
可以， 一直卡这过不去。更新了最新版本并删除config,cache，问题还是一样。
> 能够重新，不能够重现
能重现
## 你期望的结果
能解决这个问题。
> 描述以下你期望的结果
解决问题，正常运行
## 给出当前程序的配置文件

{
  "SpeedDevMode": false,
  "user_info": { "username": "admin", "password": "******" },
  "common_settings": {
    "interval_or_assign_or_custom": 0,
    "scan_interval": "@every 6h",
    "threads": 1,
    "run_scan_at_start_up": true,
    "movie_paths": ["/media/movies"],
    "series_paths": ["/media/tv"],
    "local_static_file_port": "19037"
  },
  "subtitle_sources": { "assrt_settings": { "enabled": false, "token": "" } },
  "advanced_settings": {
    "proxy_settings": {
      "use_proxy": false,
      "use_which_proxy_protocol": "http",
      "local_http_proxy_server_port": "19036",
      "input_proxy_address": "127.0.0.1",
      "input_proxy_port": "10809",
      "need_pwd": false,
      "input_proxy_username": "",
      "input_proxy_password": ""
    },
    "debug_mode": false,
    "save_full_season_tmp_subtitles": false,
    "sub_type_priority": 0,
    "sub_name_formatter": 0,
    "save_multi_sub": false,
    "custom_video_exts": [],
    "fix_time_line": false,
    "topic": 1,
    "suppliers_settings": {
      "xunlei": {
        "name": "xunlei",
        "root_url": "http://sub.xmp.sandai.net:8000/subxl/%s.json",
        "daily_download_limit": -1
      },
      "shooter": {
        "name": "shooter",
        "root_url": "https://www.shooter.cn/api/subapi.php",
        "daily_download_limit": -1
      },
      "subhd": {
        "name": "subhd",
        "root_url": "https://subhd.tv",
        "daily_download_limit": 20
      },
      "zimuku": {
        "name": "zimuku",
        "root_url": "https://zimuku.org",
        "daily_download_limit": 20
      },
      "assrt": {
        "name": "assrt",
        "root_url": "https://api.assrt.net/v1",
        "daily_download_limit": -1
      }
    },
    "scan_logic": { "skip_chinese_movie": false, "skip_chinese_series": false },
    "task_queue": {
      "max_retry_times": 3,
      "one_job_time_out": 300,
      "interval": 10,
      "expiration_time": 90,
      "download_sub_during_x_days": 7,
      "one_sub_download_interval": 12,
      "check_pulic_ip_target_site": ""
    },
    "download_file_cache": { "ttl": 4320, "unit": "hour" }
  },
  "emby_settings": {
    "enable": true,
    "address_url": "http://******:8096",
    "api_key": "**********",
    "max_request_video_number": 3000,
    "skip_watched": true,
    "movie_paths_mapping": { "/media/movies": "/data/movies" },
    "series_paths_mapping": { "/media/tv": "/data/tvshows" },
    "auto_or_manual": false,
    "threads": 4
  },
  "developer_settings": { "enable": false, "bark_server_address": "" },
  "timeline_fixer_settings": { "max_offset_time": 120, "min_offset": 0.1 },
  "experimental_function": {
    "auto_change_sub_encode": { "enable": false, "des_encode_type": 0 },
    "chs_cht_changer": { "enable": false, "des_chinese_language_type": 0 },
    "remote_chrome_settings": {
      "enable": false,
      "remote_docker_url": "",
      "remote_adblock_path": "",
      "remote_user_data_dir": ""
    },
    "api_key_settings": { "enabled": false, "key": "" },
    "local_chrome_settings": {
      "enabled": false,
      "local_chrome_exe_f_path": ""
    },
    "share_sub_settings": { "share_sub_enabled": false }
  }
}

## 如果是使用 Docker，请给出对应的配置信息

> 比如 Docker-Compose 信息，如果是其他方式使用忽略

## 请给出当次问题的完整日志

chinesesubfinder    | [INFO]: 2022-05-30 11:44:22 - Skip 速d与激情8.mp4 Sub Download, because movie has sub and downloaded or aired more than 3 months
chinesesubfinder    | [ERROR]: 2022-05-30 11:44:22 - MovieNeedDlSub.GetImdbInfo4Movie no metadata file, movie.xml or *.nfo
chinesesubfinder    | [WARNING]: 2022-05-30 11:44:22 - movie /media/movies/Doctor Strange in the Multiverse of Madness (2022)/Doctor Strange in the Multiverse of Madness (2022) TELESYNC.mkv downloadQueue isExisted
chinesesubfinder    | [WARNING]: 2022-05-30 11:44:22 - IsSubHasChinese.HasChineseLang /media/movies/【6v电影www.dy131.com】皇家赌场(未删剪版).720p.国英双语.BD中英双字.zh-cn.srt not chinese sub, is  英
chinesesubfinder    | [INFO]: 2022-05-30 11:44:22 - Skip 神q女侠.mp4 Sub Download, because movie has sub and downloaded or aired more than 3 months
chinesesubfinder    | [WARNING]: 2022-05-30 11:44:22 - IsSubHasChinese.HasChineseLang /media/movies/【6v电影www.dy131.com】皇家赌场(未删剪版).720p.国英双语.BD中英双字.zh-cn.srt not chinese sub, is  英
chinesesubfinder    | [INFO]: 2022-05-30 11:44:22 - Video Scan End
chinesesubfinder    | [INFO]: 2022-05-30 11:44:22 - ------------------------------------
chinesesubfinder    | panic: runtime error: slice bounds out of range [26:17]
chinesesubfinder    |
chinesesubfinder    | goroutine 131 [running]:
chinesesubfinder    | github.com/middelink/go-parse-torrent-name.Parse({0xc00001703e, 0x5f})
chinesesubfinder    | 	/go/pkg/mod/github.com/allanpk716/go-parse-torrent-name@v0.0.0-20220212145434-430ea25cbba7/parser.go:93 +0x293
chinesesubfinder    | github.com/allanpk716/ChineseSubFinder/internal/pkg/decode.GetVideoInfoFromFileFullPath({0xc000017030, 0x6d})
chinesesubfinder    | 	/homelab/buildspace/internal/pkg/decode/decode.go:297 +0x2c
chinesesubfinder    | github.com/allanpk716/ChineseSubFinder/internal/logic/movie_helper.MovieNeedDlSub(0x7f3d411c8108, {0xc000017030, 0x6d}, 0xc000a86270)
chinesesubfinder    | 	/homelab/buildspace/internal/logic/movie_helper/moviehelper.go:148 +0x92
chinesesubfinder    | github.com/allanpk716/ChineseSubFinder/internal/logic/sub_supplier.(*SubSupplierHub).MovieNeedDlSub(0xc00074e8d0, {0xc000017030, 0x6d}, 0x4)
chinesesubfinder    | 	/homelab/buildspace/internal/logic/sub_supplier/subSupplierHub.go:79 +0x1ae
chinesesubfinder    | github.com/allanpk716/ChineseSubFinder/internal/pkg/video_scan_and_refresh_helper.(*VideoScanAndRefreshHelper).filterMovieAndSeriesNeedDownloadEmby(0xc000210d20, 0xc0008b5aa0)
chinesesubfinder    | 	/homelab/buildspace/internal/pkg/video_scan_and_refresh_helper/video_scan_and_refresh_helper.go:961 +0x756
chinesesubfinder    | github.com/allanpk716/ChineseSubFinder/internal/pkg/video_scan_and_refresh_helper.(*VideoScanAndRefreshHelper).FilterMovieAndSeriesNeedDownload(0xc000210d20, 0xc0002a97c0)
chinesesubfinder    | 	/homelab/buildspace/internal/pkg/video_scan_and_refresh_helper/video_scan_and_refresh_helper.go:277 +0x7b
chinesesubfinder    | github.com/allanpk716/ChineseSubFinder/internal/pkg/video_scan_and_refresh_helper.(*VideoScanAndRefreshHelper).Start(0xc000210d20)
chinesesubfinder    | 	/homelab/buildspace/internal/pkg/video_scan_and_refresh_helper/video_scan_and_refresh_helper.go:99 +0x39e
chinesesubfinder    | github.com/allanpk716/ChineseSubFinder/internal/logic/cron_helper.(*CronHelper).scanVideoProcessAdd2DownloadQueue(0xc000300620)
chinesesubfinder    | 	/homelab/buildspace/internal/logic/cron_helper/cron_helper.go:272 +0xa5
chinesesubfinder    | github.com/allanpk716/ChineseSubFinder/internal/logic/cron_helper.(*CronHelper).Start(0xc000300620, 0x1)
chinesesubfinder    | 	/homelab/buildspace/internal/logic/cron_helper/cron_helper.go:140 +0xb7b
chinesesubfinder    | main.main.func2()
chinesesubfinder    | 	/homelab/buildspace/cmd/chinesesubfinder/main.go:133 +0x77
chinesesubfinder    | created by main.main
chinesesubfinder    | 	/homelab/buildspace/cmd/chinesesubfinder/main.go:131 +0x725
chinesesubfinder    | (EE)
chinesesubfinder    | Fatal server error:
chinesesubfinder    | (EE) Server is already active for display 99
chinesesubfinder    | 	If this server is no longer running, remove /tmp/.X99-lock
chinesesubfinder    | 	and start again.
chinesesubfinder    | (EE)
chinesesubfinder    | [INFO]: 2022-05-30 11:44:22 - ChineseSubFinder Version: v0.28.2
chinesesubfinder    | [INFO]: 2022-05-30 11:44:22 - Reload Log Settings, level = Info
chinesesubfinder    | [INFO]: 2022-05-30 11:44:22 - Speed Dev Mode is Off
chinesesubfinder    | [INFO]: 2022-05-30 11:44:22 - PreJob.HotFix() Start...
chinesesubfinder    | [INFO]: 2022-05-30 11:44:22 - If you have a lot of videos, it may take a lot of time, just wait...
chinesesubfinder    | [INFO]: 2022-05-30 11:44:23 - PreJob.HotFix() End
chinesesubfinder    | [INFO]: 2022-05-30 11:44:23 - PreJob.ChangeSubNameFormat() Start...
chinesesubfinder    | [INFO]: 2022-05-30 11:44:23 - If you have a lot of videos, it may take a lot of time, just wait...
chinesesubfinder    | [INFO]: 2022-05-30 11:44:23 - DesSubFormatter == LateTimeSubFormatter then skip process
chinesesubfinder    | [INFO]: 2022-05-30 11:44:23 - PreJob.ChangeSubNameFormat() End
chinesesubfinder    | [INFO]: 2022-05-30 11:44:23 - PreJob.ReloadBrowser() Start...
chinesesubfinder    | [INFO]: 2022-05-30 11:44:23 - releaseAdblock start
chinesesubfinder    | [INFO]: 2022-05-30 11:44:23 - releaseAdblock end
chinesesubfinder    | [cont-finish.d] executing container finish scripts...
chinesesubfinder    | [cont-finish.d] done.
chinesesubfinder    | [s6-finish] waiting for services.
chinesesubfinder    | [s6-finish] sending all processes the TERM signal.
chinesesubfinder    | [s6-finish] sending all processes the KILL signal and exiting.

**Comment by boer0327** [comment]
不好意思忘记填docker compose的配置了

`  chinesesubfinder:
    image: allanpk716/chinesesubfinder:latest
    container_name: chinesesubfinder
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Asia/Shanghai
    volumes:
      - /volume1/media:/media
      - /volume2/docker/chinesesubfinder/config:/config
      - /volume2/docker/chinesesubfinder/cache:/cache
    ports:
      - 19035:19035
    restart: unless-stopped`

这是在群晖上运行的。这个uid/pid是没有问题的。 之前已经正常的运行了一个多星期了。

**Comment by allanpk716** [comment]
升级最新 v0.29.2 ，先看是否还有故障，如果还有开启 debug 再发送对应一段故障的日志给我看看。

**Comment by boer0327** [comment]
好的， 多谢，多谢。 我先升级一下docker,  然后再看看文档咋开启debug. 稍后回复你。

**Comment by boer0327** [comment]
> 升级最新 v0.29.2 ，先看是否还有故障，如果还有开启 debug 再发送对应一段故障的日志给我看看。
> 
> 看起来是第三方库故障了，开启 debug 可以直到具体是处理到那一步和数据触发的。

不好意思， 在文档里面没有看到哪个参数是开启debug模式？我更新了最新版本还是提示这个错误， 所以我想开启一下debug模式，看一下具体是哪里错，然后再发你。麻烦能告诉我一下啥参数开启debug模式。多谢多谢。

**Comment by boer0327** [comment]
我知道问题了， 我的web UI是打不开的。 但是我试着修改了ChineseSubFinderSettings.json。 里面的debug_mode : true, 试着运行， 好像还不是在debug模式下运行。很奇怪。日志也差不多


chinesesubfinder    | [INFO]: 2022-05-30 14:30:41 - Skip [BD影视分享bd2020.com]Eternals.2021.IMAX.AAC5.1.HD1080P.官方中英双字.mp4 Sub Download, because movie has sub and downloaded or aired more than 3 months
chinesesubfinder    | [DEBUG]: 2022-05-30 14:30:41 - DetermineFileTypeFromFile ass /media/movies/【6v电影www.dy131.com】皇家赌场(未删剪版).720p.国英双语.BD中英双字.1.chinese(简).srt
chinesesubfinder    | [DEBUG]: 2022-05-30 14:30:41 - DetermineFileTypeFromBytes can't found DialoguesFilter, Skip
chinesesubfinder    | [DEBUG]: 2022-05-30 14:30:41 - DetermineFileTypeFromFile srt /media/movies/【6v电影www.dy131.com】皇家赌场(未删剪版).720p.国英双语.BD中英双字.1.chinese(简).srt
chinesesubfinder    | [DEBUG]: 2022-05-30 14:30:41 - DetermineFileTypeFromFile ass /media/movies/【6v电影www.dy131.com】皇家赌场(未删剪版).720p.国英双语.BD中英双字.zh-cn.srt
chinesesubfinder    | [DEBUG]: 2022-05-30 14:30:41 - DetermineFileTypeFromBytes can't found DialoguesFilter, Skip
chinesesubfinder    | [DEBUG]: 2022-05-30 14:30:41 - DetermineFileTypeFromFile srt /media/movies/【6v电影www.dy131.com】皇家赌场(未删剪版).720p.国英双语.BD中英双字.zh-cn.srt
chinesesubfinder    | [WARNING]: 2022-05-30 14:30:41 - IsSubHasChinese.HasChineseLang /media/movies/【6v电影www.dy131.com】皇家赌场(未删剪版).720p.国英双语.BD中英双字.zh-cn.srt not chinese sub, is  英
chinesesubfinder    | [DEBUG]: 2022-05-30 14:30:41 - DetermineFileTypeFromFile ass /media/movies/寻龙传说.Raya.and.the.Last.Dragon.HD1080P.X264.AAC.English.CHS-ENG.chinese(简).srt
chinesesubfinder    | [DEBUG]: 2022-05-30 14:30:41 - DetermineFileTypeFromBytes can't found DialoguesFilter, Skip
chinesesubfinder    | [DEBUG]: 2022-05-30 14:30:41 - DetermineFileTypeFromFile srt /media/movies/寻龙传说.Raya.and.the.Last.Dragon.HD1080P.X264.AAC.English.CHS-ENG.chinese(简).srt
chinesesubfinder    | [DEBUG]: 2022-05-30 14:30:41 - DetermineFileTypeFromFile ass /media/movies/摔j吧！爸爸[DVD版].1.未知语言 推荐等级_★★★.ass
chinesesubfinder    | [DEBUG]: 2022-05-30 14:30:41 - DetermineFileTypeFromFile ass /media/movies/摔j吧！爸爸[DVD版].2.简体 推荐等级_☆.srt
chinesesubfinder    | [DEBUG]: 2022-05-30 14:30:41 - DetermineFileTypeFromBytes can't found DialoguesFilter, Skip
chinesesubfinder    | [DEBUG]: 2022-05-30 14:30:41 - DetermineFileTypeFromFile srt /media/movies/摔j吧！爸爸[DVD版].2.简体 推荐等级_☆.srt
chinesesubfinder    | [DEBUG]: 2022-05-30 14:30:41 - DetermineFileTypeFromFile ass /media/movies/美n与野兽.1.简体 推荐等级_★★★.srt
chinesesubfinder    | [DEBUG]: 2022-05-30 14:30:41 - DetermineFileTypeFromBytes can't found DialoguesFilter, Skip
chinesesubfinder    | [DEBUG]: 2022-05-30 14:30:41 - DetermineFileTypeFromFile srt /media/movies/美n与野兽.1.简体 推荐等级_★★★.srt
chinesesubfinder    | [DEBUG]: 2022-05-30 14:30:41 - DetermineFileTypeFromFile ass /media/movies/速d与激情8.2.简体 推荐等级_☆.srt
chinesesubfinder    | [DEBUG]: 2022-05-30 14:30:41 - DetermineFileTypeFromBytes can't found DialoguesFilter, Skip
chinesesubfinder    | [DEBUG]: 2022-05-30 14:30:41 - DetermineFileTypeFromFile srt /media/movies/速d与激情8.2.简体 推荐等级_☆.srt
chinesesubfinder    | [INFO]: 2022-05-30 14:30:41 - Video Scan End
chinesesubfinder    | [INFO]: 2022-05-30 14:30:41 - ------------------------------------
chinesesubfinder    | panic: runtime error: slice bounds out of range [26:17]
chinesesubfinder    |
chinesesubfinder    | goroutine 81 [running]:
chinesesubfinder    | github.com/middelink/go-parse-torrent-name.Parse({0xc0008ae31e, 0x5f})
chinesesubfinder    | 	/go/pkg/mod/github.com/allanpk716/go-parse-torrent-name@v0.0.0-20220212145434-430ea25cbba7/parser.go:93 +0x293
chinesesubfinder    | github.com/allanpk716/ChineseSubFinder/internal/pkg/decode.GetVideoInfoFromFileFullPath({0xc0008ae310, 0x6d})
chinesesubfinder    | 	/homelab/buildspace/internal/pkg/decode/decode.go:297 +0x2c
chinesesubfinder    | github.com/allanpk716/ChineseSubFinder/internal/logic/movie_helper.MovieNeedDlSub(0x7f3e83cbe5b8, {0xc0008ae310, 0x6d}, 0xc0009f6300)
chinesesubfinder    | 	/homelab/buildspace/internal/logic/movie_helper/moviehelper.go:148 +0x92
chinesesubfinder    | github.com/allanpk716/ChineseSubFinder/internal/logic/sub_supplier.(*SubSupplierHub).MovieNeedDlSub(0xc0005eb710, {0xc0008ae310, 0x6d}, 0x4)
chinesesubfinder    | 	/homelab/buildspace/internal/logic/sub_supplier/subSupplierHub.go:79 +0x1ae
chinesesubfinder    | github.com/allanpk716/ChineseSubFinder/internal/pkg/video_scan_and_refresh_helper.(*VideoScanAndRefreshHelper).filterMovieAndSeriesNeedDownloadEmby(0xc00046d200, 0xc00012b880)
chinesesubfinder    | 	/homelab/buildspace/internal/pkg/video_scan_and_refresh_helper/video_scan_and_refresh_helper.go:961 +0x756
chinesesubfinder    | github.com/allanpk716/ChineseSubFinder/internal/pkg/video_scan_and_refresh_helper.(*VideoScanAndRefreshHelper).FilterMovieAndSeriesNeedDownload(0xc00046d200, 0xc00090a000)
chinesesubfinder    | 	/homelab/buildspace/internal/pkg/video_scan_and_refresh_helper/video_scan_and_refresh_helper.go:277 +0x7b
chinesesubfinder    | github.com/allanpk716/ChineseSubFinder/internal/pkg/video_scan_and_refresh_helper.(*VideoScanAndRefreshHelper).Start(0xc00046d200)
chinesesubfinder    | 	/homelab/buildspace/internal/pkg/video_scan_and_refresh_helper/video_scan_and_refresh_helper.go:99 +0x39e
chinesesubfinder    | github.com/allanpk716/ChineseSubFinder/internal/logic/cron_helper.(*CronHelper).scanVideoProcessAdd2DownloadQueue(0xc0002b2a80)
chinesesubfinder    | 	/homelab/buildspace/internal/logic/cron_helper/cron_helper.go:288 +0xa5
chinesesubfinder    | github.com/allanpk716/ChineseSubFinder/internal/logic/cron_helper.(*CronHelper).Start(0xc0002b2a80, 0x1)
chinesesubfinder    | 	/homelab/buildspace/internal/logic/cron_helper/cron_helper.go:156 +0xd1b
chinesesubfinder    | main.main.func2()
chinesesubfinder    | 	/homelab/buildspace/cmd/chinesesubfinder/main.go:131 +0x77
chinesesubfinder    | created by main.main
chinesesubfinder    | 	/homelab/buildspace/cmd/chinesesubfinder/main.go:129 +0x725
chinesesubfinder    | (EE)
chinesesubfinder    | Fatal server error:
chinesesubfinder    | (EE) Server is already active for display 99
chinesesubfinder    | 	If this server is no longer running, remove /tmp/.X99-lock
chinesesubfinder    | 	and start again.
chinesesubfinder    | (EE)
chinesesubfinder    | [INFO]: 2022-05-30 14:30:41 - ChineseSubFinder Version: v0.29.2
chinesesubfinder    | [INFO]: 2022-05-30 14:30:41 - Reload Log Settings, level = Debug
chinesesubfinder    | [INFO]: 2022-05-30 14:30:41 - Speed Dev Mode is Off
chinesesubfinder    | [INFO]: 2022-05-30 14:30:41 - PreJob.HotFix() Start...
chinesesubfinder    | [INFO]: 2022-05-30 14:30:41 - If you have a lot of videos, it may take a lot of time, just wait...

**Comment by allanpk716** [comment]
1. 你现在的视频都没有经过削刮对于命名进行处理，还是是内嵌字幕的，所以我不清楚你的目标是全部都下载字幕还是部分下载？
2. 因为命名的规范问题，那么就有可能在第三方库读取视频文件名解析的时候就故障了（毕竟是国外人针对有一定命名规范做的解析器）。
3. 就算我解决了第三方库的bug，依然不能正确解析出有效的文件名信息，所以字幕搜索效果依然没有保障。

我个人的建议是，如果你想要正常使用，那么就看看其他人的自动化追剧教程：

https://sleele.com/tag/%e9%ab%98%e9%98%b6%e6%95%99%e7%a8%8b-%e8%bf%bd%e5%89%a7%e5%85%a8%e6%b5%81%e7%a8%8b%e8%87%aa%e5%8a%a8%e5%8c%96/

https://johnrosen1.com/2022/03/18/media/

这两篇我觉得足够满足日常自动化追剧（我不看中文剧集不能确定是否能搞定）

**Comment by boer0327** [comment]
嗯， 我也看了一下， 你用到的那个库报的一个issue， 我想也是应该是命名的问题。 我的剧都很规范。 呵呵。 因为都是用sonnor 下载的。 我想问题主要出在电影上面。 因为电影是很早就下载的，就没有规范命名。 

但是这里很奇怪的是我这个一直很好的用了快有个把星期了。一直没问题。然后周末才发现这个问题的。

好，我试着去规范一下电影目录的问题。

多谢多谢。

**Comment by allanpk716** [comment]
我等下会推送一版，估计1个小时后可以看到最新的 v0.29.3

**Comment by boer0327** [comment]
好的， 多谢， 我先去整理一下我的电影，晚一点再试一下你的更新， 多谢多谢。

**Comment by allanpk716** [comment]
> 好的， 多谢， 我先去整理一下我的电影，晚一点再试一下你的更新， 多谢多谢。

也谢谢你的反馈。 😂

**Comment by boer0327** [comment]
呵呵， 你的工具做的真的很不错啊， 基本解决了追剧的最后一环啊。

**Comment by boer0327** [comment]
最新版本已经解决了这个问题，多谢多谢。
