### ISSUE TITLE
异常崩溃

### ISSUE THREAD

**Issue by Chuanbin-Wang** [allanpk716/ChineseSubFinder#471]
## 你使用的 chinesesubfinder 是什么版本，什么环境？
docker v0.35.1 

## 你遇到什么问题了？
更新缓存时崩溃

## 你的问题弄重现嘛？
可以

## 你期望的结果
正常更新缓存

## 给出当前程序的配置文件
```json
{
	"SpeedDevMode": true,
	"common_settings": {
		"interval_or_assign_or_custom": 0,
		"scan_interval": "@every 6h",
		"threads": 1,
		"run_scan_at_start_up": true,
		"movie_paths": ["/media/archive", "/media/movies"],
		"series_paths": ["/media/tv"],
		"local_static_file_port": "19037"
	},
	"subtitle_sources": {
		"assrt_settings": {
			"enabled": false,
			"token": ""
		}
	},
	"advanced_settings": {
		"proxy_settings": {
			"use_proxy": true,
			"use_which_proxy_protocol": "http",
			"local_http_proxy_server_port": "19036",
			"input_proxy_address": "10.0.0.2",
			"input_proxy_port": "1081",
			"need_pwd": false,
			"input_proxy_username": "",
			"input_proxy_password": ""
		},
		"debug_mode": true,
		"save_full_season_tmp_subtitles": false,
		"sub_type_priority": 0,
		"sub_name_formatter": 1,
		"save_multi_sub": false,
		"custom_video_exts": [],
		"fix_time_line": false,
		"topic": 1,
		"suppliers_settings": {
			"csf": {
				"name": "csf",
				"root_url": "haha",
				"daily_download_limit": -1
			},
			"xunlei": {
				"name": "xunlei",
				"root_url": "http://sub.xmp.sandai.net:8000/subxl/%s.json",
				"daily_download_limit": -1
			},
			"shooter": {
				"name": "shooter",
				"root_url": "https://www.shooter.cn/api/subapi.php",
				"daily_download_limit": -1
			},
			"subhd": {
				"name": "subhd",
				"root_url": "https://subhd.tv",
				"daily_download_limit": 20
			},
			"zimuku": {
				"name": "zimuku",
				"root_url": "https://zimuku.org",
				"daily_download_limit": 20
			},
			"assrt": {
				"name": "assrt",
				"root_url": "https://api.assrt.net/v1",
				"daily_download_limit": -1
			},
			"a4k": {
				"name": "a4k",
				"root_url": "https://www.a4k.net",
				"daily_download_limit": -1
			}
		},
		"scan_logic": {
			"skip_chinese_movie": true,
			"skip_chinese_series": true
		},
		"task_queue": {
			"max_retry_times": 3,
			"one_job_time_out": 300,
			"interval": 10,
			"expiration_time": 90,
			"download_sub_during_x_days": 7,
			"one_sub_download_interval": 12,
			"check_pulic_ip_target_site": ""
		},
		"download_file_cache": {
			"ttl": 4320,
			"unit": "hour"
		}
	},
	"emby_settings": {
		"enable": true,
		"address_url": "http://jellyfin:8096",
		"api_key": "6eb279570f8e4296b29314252058f9a3",
		"max_request_video_number": 500,
		"skip_watched": false,
		"movie_paths_mapping": {
			"/media/archive": "",
			"/media/movies": ""
		},
		"series_paths_mapping": {
			"/media/tv": ""
		},
		"auto_or_manual": true,
		"threads": 6
	},
	"developer_settings": {
		"enable": false,
		"bark_server_address": ""
	},
	"timeline_fixer_settings": {
		"max_offset_time": 700,
		"min_offset": 0.2
	},
	"experimental_function": {
		"auto_change_sub_encode": {
			"enable": false,
			"des_encode_type": 0
		},
		"chs_cht_changer": {
			"enable": false,
			"des_chinese_language_type": 0
		},
		"remote_chrome_settings": {
			"enable": false,
			"remote_docker_url": "",
			"remote_adblock_path": "",
			"remote_user_data_dir": ""
		},
		"api_key_settings": {
			"enabled": false,
			"key": ""
		},
		"local_chrome_settings": {
			"enabled": false,
			"local_chrome_exe_f_path": ""
		},
		"share_sub_settings": {
			"share_sub_enabled": false
		}
	}
}
```

## 如果是使用 Docker，请给出对应的配置信息
```
chinesesubfinder:
    image: allanpk716/chinesesubfinder:v0.35.1
    container_name: chinesesubfinder
    volumes:
      - /mnt/storage/chinesesubfinder:/config
      - /mnt/media:/media
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
    restart: unless-stopped
```

## 给出媒体文件夹的目录结构
![图片](https://user-images.githubusercontent.com/76732400/186354071-8e3e96ae-40ee-4834-bdd2-d59896229800.png)

## 请给出当次问题的完整日志
```
[DEBUG]: 2022-08-24 15:07:52 - Index: 9 baseFuncHandler cancelMapLock Lock()

[DEBUG]: 2022-08-24 15:07:52 - Index: 9 baseFuncHandler cancelMapLock UnLock()

[INFO]: 2022-08-24 15:07:52 - updateLocalVideoCacheInfo 9 /media/tv/舌尖上的中国/第一季

[DEBUG]: 2022-08-24 15:07:52 - GetIMDBInfoFromVideoNfoInfo IMDBID: tt2168980 TMDBID: 60781 舌尖上的中国 -1 -1

[DEBUG]: 2022-08-24 15:07:52 - GetIMDBInfoFromVideoNfoInfo 0

[DEBUG]: 2022-08-24 15:07:52 - GetIMDBInfoFromVideoNfoInfo 1

[DEBUG]: 2022-08-24 15:07:52 - GetIMDBInfoFromVideoNfoInfo 4

[DEBUG]: 2022-08-24 15:07:52 - Index: 9 baseFuncHandler cancelMapLock Lock() defer

[DEBUG]: 2022-08-24 15:07:52 - Index: 9 baseFuncHandler cancelMapLock UnLock() defer

[DEBUG]: 2022-08-24 15:07:52 - Index: 9 baseFuncHandler wg.Done()

[INFO]: 2022-08-24 15:07:52 - ScanNormalMovieAndSeries End

[INFO]: 2022-08-24 15:07:52 - ScanEmbyMovieAndSeries Start...

[INFO]: 2022-08-24 15:07:52 - Forced Scan And DownSub, tmpSetting.EmbySettings.MaxRequestVideoNumber = 1000000

[INFO]: 2022-08-24 15:07:52 - ScanEmbyMovieAndSeries End

[INFO]: 2022-08-24 15:07:52 - Video Scan Finished By webui, cost: 0.0250006613 min

[INFO]: 2022-08-24 15:07:52 - ------------------------------------

panic: sync/atomic: store of nil value into Value


goroutine 190 [running]:

sync/atomic.(*Value).Store(0x0, {0x0, 0x0})

	/opt/hostedtoolcache/go/1.17.11/x64/src/sync/atomic/value.go:47 +0xeb

github.com/huandu/go-clone.init.0.func4({0x1138480, 0xc0001e4048, 0xc0001e4028}, {0x1138480, 0xc00097aa70, 0xc0009827d4})

	/home/runner/go/pkg/mod/github.com/huandu/go-clone@v1.3.0/structtype.go:84 +0xf5

github.com/huandu/go-clone.(*structType).Copy(0xc000d18ad8, {0x1138480, 0xc0001e4048, 0x20b5920}, {0x114c4c0, 0xc00097aa70, 0x40fe74})

	/home/runner/go/pkg/mod/github.com/huandu/go-clone@v1.3.0/structtype.go:163 +0xfe

github.com/huandu/go-clone.(*cloneState).copyStruct(0x0, {0x1138480, 0xc0001e4048, 0x18d5c90}, {0x114c4c0, 0xc00097aa70, 0xc000728000})

	/home/runner/go/pkg/mod/github.com/huandu/go-clone@v1.3.0/clone.go:293 +0x105

github.com/huandu/go-clone.(*cloneState).cloneStruct(0x0, {0x1138480, 0xc0001e4048, 0xc0001f9540})

	/home/runner/go/pkg/mod/github.com/huandu/go-clone@v1.3.0/clone.go:284 +0x85

github.com/huandu/go-clone.(*cloneState).clone(0x1230fe0, {0x1138480, 0xc0001e4048, 0xc0001f9580})

	/home/runner/go/pkg/mod/github.com/huandu/go-clone@v1.3.0/clone.go:94 +0x14e

github.com/huandu/go-clone.(*cloneState).copyStruct(0x0, {0x1230fe0, 0xc0001e4000, 0xc00097a8c0}, {0x121e540, 0xc0001f9540, 0x0})

	/home/runner/go/pkg/mod/github.com/huandu/go-clone@v1.3.0/clone.go:335 +0x417

github.com/huandu/go-clone.(*cloneState).clonePtr(0x0, {0x121e540, 0xc000dc4078, 0xc00086fb80})

	/home/runner/go/pkg/mod/github.com/huandu/go-clone@v1.3.0/clone.go:212 +0x39a

github.com/huandu/go-clone.(*cloneState).clone(0x1209a20, {0x121e540, 0xc000dc4078, 0xc00086fbe0})

	/home/runner/go/pkg/mod/github.com/huandu/go-clone@v1.3.0/clone.go:90 +0x12b

github.com/huandu/go-clone.(*cloneState).copyStruct(0x0, {0x1209a20, 0xc000dc4000, 0xc000527038}, {0x11f59a0, 0xc00086fb80, 0x812615})

	/home/runner/go/pkg/mod/github.com/huandu/go-clone@v1.3.0/clone.go:335 +0x417

github.com/huandu/go-clone.(*cloneState).clonePtr(0x0, {0x11f59a0, 0xc000dc4000, 0x108b320})

	/home/runner/go/pkg/mod/github.com/huandu/go-clone@v1.3.0/clone.go:212 +0x39a

github.com/huandu/go-clone.(*cloneState).clone(0x111bdc0, {0x11f59a0, 0xc000dc4000, 0x18d5c90})

	/home/runner/go/pkg/mod/github.com/huandu/go-clone@v1.3.0/clone.go:90 +0x12b

github.com/huandu/go-clone.(*cloneState).cloneInterface(0x1222fa0, {0x111bdc0, 0xc000ac8010, 0xc00035f0a0})

	/home/runner/go/pkg/mod/github.com/huandu/go-clone@v1.3.0/clone.go:128 +0x10b

github.com/huandu/go-clone.(*cloneState).clone(0x1222fa0, {0x111bdc0, 0xc000ac8010, 0x20b5920})

	/home/runner/go/pkg/mod/github.com/huandu/go-clone@v1.3.0/clone.go:86 +0x92

github.com/huandu/go-clone.(*cloneState).copyStruct(0x0, {0x1222fa0, 0xc000ac8000, 0x20}, {0x121e320, 0xc00035f0a0, 0x11b3f20})

	/home/runner/go/pkg/mod/github.com/huandu/go-clone@v1.3.0/clone.go:335 +0x417

github.com/huandu/go-clone.(*cloneState).clonePtr(0x0, {0x121e320, 0xc0009b21b0, 0xc000b103f0})

	/home/runner/go/pkg/mod/github.com/huandu/go-clone@v1.3.0/clone.go:212 +0x39a

github.com/huandu/go-clone.(*cloneState).clone(0x11b3f20, {0x121e320, 0xc0009b21b0, 0x20b5920})

	/home/runner/go/pkg/mod/github.com/huandu/go-clone@v1.3.0/clone.go:90 +0x12b

github.com/huandu/go-clone.(*cloneState).copyStruct(0x0, {0x11b3f20, 0xc0009b21b0, 0x4c99a5}, {0x11255c0, 0xc000b103f0, 0x12047c0})

	/home/runner/go/pkg/mod/github.com/huandu/go-clone@v1.3.0/clone.go:335 +0x417

github.com/huandu/go-clone.(*cloneState).clonePtr(0x0, {0x11255c0, 0xc000196230, 0xc000196ea0})

	/home/runner/go/pkg/mod/github.com/huandu/go-clone@v1.3.0/clone.go:212 +0x39a

github.com/huandu/go-clone.(*cloneState).clone(0x12047c0, {0x11255c0, 0xc000196230, 0x20b5920})

	/home/runner/go/pkg/mod/github.com/huandu/go-clone@v1.3.0/clone.go:90 +0x12b

github.com/huandu/go-clone.(*cloneState).copyStruct(0x0, {0x12047c0, 0xc0001961b0, 0x5}, {0x1125840, 0xc000196ea0, 0x120e140})

	/home/runner/go/pkg/mod/github.com/huandu/go-clone@v1.3.0/clone.go:335 +0x417

github.com/huandu/go-clone.(*cloneState).clonePtr(0x0, {0x1125840, 0xc00081c540, 0xc00046dd50})

	/home/runner/go/pkg/mod/github.com/huandu/go-clone@v1.3.0/clone.go:212 +0x39a

github.com/huandu/go-clone.(*cloneState).clone(0x120e140, {0x1125840, 0xc00081c540, 0x20b5920})

	/home/runner/go/pkg/mod/github.com/huandu/go-clone@v1.3.0/clone.go:90 +0x12b

github.com/huandu/go-clone.(*cloneState).copyStruct(0x0, {0x120e140, 0xc00081c540, 0x1}, {0x1069800, 0xc00046dd50, 0x11fea60})

	/home/runner/go/pkg/mod/github.com/huandu/go-clone@v1.3.0/clone.go:335 +0x417

github.com/huandu/go-clone.(*cloneState).clonePtr(0x0, {0x1069800, 0xc0000f89f0, 0xc000b77080})

	/home/runner/go/pkg/mod/github.com/huandu/go-clone@v1.3.0/clone.go:212 +0x39a

github.com/huandu/go-clone.(*cloneState).clone(0x11fea60, {0x1069800, 0xc0000f89f0, 0xc000b770a8})

	/home/runner/go/pkg/mod/github.com/huandu/go-clone@v1.3.0/clone.go:90 +0x12b

github.com/huandu/go-clone.(*cloneState).copyStruct(0x0, {0x11fea60, 0xc0000f89c0, 0xc00023ac60}, {0x11485a0, 0xc000b77080, 0x203000})

	/home/runner/go/pkg/mod/github.com/huandu/go-clone@v1.3.0/clone.go:335 +0x417

github.com/huandu/go-clone.(*cloneState).clonePtr(0x0, {0x11485a0, 0xc0000f89c0, 0xc000527d40})

	/home/runner/go/pkg/mod/github.com/huandu/go-clone@v1.3.0/clone.go:212 +0x39a

github.com/huandu/go-clone.(*cloneState).clone(0xc00046c070, {0x11485a0, 0xc0000f89c0, 0x122c780})

	/home/runner/go/pkg/mod/github.com/huandu/go-clone@v1.3.0/clone.go:90 +0x12b

github.com/huandu/go-clone.Clone({0x11485a0, 0xc0000f89c0})

	/home/runner/go/pkg/mod/github.com/huandu/go-clone@v1.3.0/clone.go:36 +0xa8

github.com/allanpk716/ChineseSubFinder/pkg/video_scan_and_refresh_helper.(*VideoScanAndRefreshHelper).ScanEmbyMovieAndSeries(0xc000342620, 0xc00097a240)

	/home/runner/work/ChineseSubFinder/ChineseSubFinder/pkg/video_scan_and_refresh_helper/video_scan_and_refresh_helper.go:263 +0x146

github.com/allanpk716/ChineseSubFinder/internal/backend/controllers/v1.(*ControllerBase).RefreshVideoListHandler.func2()

	/home/runner/work/ChineseSubFinder/ChineseSubFinder/internal/backend/controllers/v1/video_list.go:73 +0x293

created by github.com/allanpk716/ChineseSubFinder/internal/backend/controllers/v1.(*ControllerBase).RefreshVideoListHandler

	/home/runner/work/ChineseSubFinder/ChineseSubFinder/internal/backend/controllers/v1/video_list.go:51 +0x105
```

**Comment by allanpk716** [comment]
目录不对，看教程

**Comment by Chuanbin-Wang** [comment]
按照文档说明，目录结构不对的话是被跳过，这个没问题。崩溃不应该

**Comment by allanpk716** [comment]
那就尝试升级到最新看看， clone 这个方法之前有问题

**Comment by Chuanbin-Wang** [comment]
新版本不崩了
