### ISSUE TITLE
无法连接api.subtitle.best导致程序崩溃

### ISSUE THREAD

**Issue by kunger97** [allanpk716/ChineseSubFinder#472]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: v0.38.3
>
> 环境: Linux
>

## 你遇到什么问题了？

> 程序输出dial tcp: lookup api.subtitle.best on 8.8.4.4:53: read udp [My-Server-IP]:47855->8.8.4.4:53: i/o timeout后崩溃

## 你的问题弄重现嘛？

>未进行复现

## 你期望的结果

> 进行错误处理避免程序退出

## 给出当前程序的配置文件

```json
{
   "SpeedDevMode":false,
   "user_info":{
   },
   "common_settings":{
      "interval_or_assign_or_custom":0,
      "scan_interval":"@every 6h",
      "threads":6,
      "run_scan_at_start_up":true,
      "movie_paths":[
         "/nfs/NAS-01/AnimeMovie",
         "/nfs/CNBOY/AnimeMovie"
      ],
      "series_paths":[
         "/nfs/NAS-01/AnimeEpisodes"
      ],
      "local_static_file_port":"19037"
   },
   "subtitle_sources":{
      "assrt_settings":{
         "enabled":true,
      }
   },
   "advanced_settings":{
      "proxy_settings":{
         "use_proxy":false,
         "use_which_proxy_protocol":"http",
         "local_http_proxy_server_port":"19036",
         "input_proxy_address":"127.0.0.1",
         "input_proxy_port":"10809",
         "need_pwd":false,
         "input_proxy_username":"",
         "input_proxy_password":""
      },
      "debug_mode":false,
      "save_full_season_tmp_subtitles":false,
      "sub_type_priority":0,
      "sub_name_formatter":0,
      "save_multi_sub":false,
      "custom_video_exts":[
         
      ],
      "fix_time_line":false,
      "topic":1,
      "suppliers_settings":{
         "csf":{
            "name":"csf",
            "root_url":"haha",
            "daily_download_limit":-1
         },
         "xunlei":{
            "name":"xunlei",
            "root_url":"http://sub.xmp.sandai.net:8000/subxl/%s.json",
            "daily_download_limit":-1
         },
         "shooter":{
            "name":"shooter",
            "root_url":"https://www.shooter.cn/api/subapi.php",
            "daily_download_limit":-1
         },
         "subhd":{
            "name":"subhd",
            "root_url":"https://subhd.tv",
            "daily_download_limit":20
         },
         "zimuku":{
            "name":"zimuku",
            "root_url":"https://zimuku.org",
            "daily_download_limit":20
         },
         "assrt":{
            "name":"assrt",
            "root_url":"https://api.assrt.net/v1",
            "daily_download_limit":-1
         },
         "a4k":{
            "name":"a4k",
            "root_url":"https://www.a4k.net",
            "daily_download_limit":-1
         }
      },
      "scan_logic":{
         "skip_chinese_movie":true,
         "skip_chinese_series":true
      },
      "task_queue":{
         "max_retry_times":3,
         "one_job_time_out":300,
         "interval":10,
         "expiration_time":90,
         "download_sub_during_x_days":7,
         "one_sub_download_interval":12,
         "check_pulic_ip_target_site":""
      },
      "download_file_cache":{
         "ttl":4320,
         "unit":"hour"
      }
   },
   "emby_settings":{
      "enable":true,
      "address_url":"http://localhost",
      "max_request_video_number":3000,
      "skip_watched":true,
      "movie_paths_mapping":{
         "/nfs/CNBOY/AnimeMovie":"",
         "/nfs/NAS-01/AnimeMovie":""
      },
      "series_paths_mapping":{
         "/nfs/NAS-01/AnimeEpisodes":""
      },
      "auto_or_manual":true,
      "threads":6
   },
   "developer_settings":{
      "enable":false,
      "bark_server_address":""
   },
   "timeline_fixer_settings":{
      "max_offset_time":700,
      "min_offset":0.2
   },
   "experimental_function":{
      "auto_change_sub_encode":{
         "enable":false,
         "des_encode_type":0
      },
      "chs_cht_changer":{
         "enable":false,
         "des_chinese_language_type":0
      },
      "remote_chrome_settings":{
         "enable":false,
         "remote_docker_url":"",
         "remote_adblock_path":"",
         "remote_user_data_dir":""
      },
      "api_key_settings":{
         "enabled":false,
         "key":""
      },
      "local_chrome_settings":{
         "enabled":false,
         "local_chrome_exe_f_path":""
      },
      "share_sub_settings":{
         "share_sub_enabled":true
      },
      "extend_log":{
         "SysLog":{
            "enable":false,
            "network":"",
            "address":"",
            "priority":0,
            "tag":""
         }
      }
   }
}
```
## 请给出当次问题的完整日志

```
[INFO]: 2022-08-24 12:32:32 - UploadSub [DMG&VCB-Studio] Eiga Daisuki Pompo-san [Ma10p_1080p][x265_flac_aac].tc.ass
2022/08/24 12:32:52.529314 ERROR RESTY Post "https://api.subtitle.best/v1/upload-sub": dial tcp: lookup api.subtitle.best on 8.8.4.4:53: read udp [My-Server-IP]:47855->8.8.4.4:53: i/o timeout, Attempt 1
2022/08/24 12:32:52.629726 ERROR RESTY EOF, Attempt 2
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x8c85b9]

goroutine 12850 [running]:
github.com/go-resty/resty/v2.(*Response).StatusCode(...)
	/home/runner/go/pkg/mod/github.com/go-resty/resty/v2@v2.6.0/response.go:52
github.com/allanpk716/ChineseSubFinder/pkg/subtitle_best_api.(*SubtitleBestApi).UploadLowTrustSub(0xc000942500, 0xc0009dc000, {0xc000589040, 0x1d}, {0xc000c19338, 0x6}, {0xc0000ee0d4, 0x4}, {0x0, 0x0})
	/home/runner/work/ChineseSubFinder/ChineseSubFinder/pkg/subtitle_best_api/subtitle_best_api.go:382 +0x1099
github.com/allanpk716/ChineseSubFinder/pkg/logic/cron_helper.(*CronHelper).uploadLowTrustVideoSub(0xc00094c880)
	/home/runner/work/ChineseSubFinder/ChineseSubFinder/pkg/logic/cron_helper/upload_played_video_sub.go:361 +0x1394
github.com/allanpk716/ChineseSubFinder/pkg/logic/cron_helper.(*CronHelper).uploadVideoSub(0xc0b99d6e800cbf8f)
	/home/runner/work/ChineseSubFinder/ChineseSubFinder/pkg/logic/cron_helper/upload_played_video_sub.go:25 +0x28
github.com/robfig/cron/v3.FuncJob.Run(0x408400)
	/home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/cron.go:131 +0x1a
github.com/robfig/cron/v3.DelayIfStillRunning.func1.1()
	/home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/chain.go:71 +0x1aa
github.com/robfig/cron/v3.FuncJob.Run(0xc000ee4630)
	/home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/cron.go:131 +0x1a
github.com/robfig/cron/v3.(*Cron).startJob.func1()
	/home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/cron.go:307 +0x6a
created by github.com/robfig/cron/v3.(*Cron).startJob
	/home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/cron.go:305 +0xb2
```

**Comment by allanpk716** [comment]
推送了 v0.38.4，试试。
