### ISSUE TITLE
docker 无法启动 fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by Lartry** [allanpk716/ChineseSubFinder#488]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: vx.x.x
> 0.39.0
> 环境: docker or Window or Linux or MAC
> 远程服务器linux 本地 windows 
> 在程序运行日志头部或者 Web UI 可以看到

## 你遇到什么问题了？
```
fatal error: unexpected signal during runtime execution 
```
> 描述一下你遇到的问题
无法正常启动, 在国内本地环境下可以启动成功. 远程服务器上无法启动, 
```
服务器系统版本
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

国内本地版本
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

```
## 你的问题弄重现嘛？
能
> 能够重现，不能够重现
能够重现
## 你期望的结果
正常运行
> 描述以下你期望的结果
正常启动运行
## 给出当前程序的配置文件
无配置文件,未产生
> /volume1/docker/chinesesubfinder/config:/config 下，ChineseSubFinderSettings.json，记得把你的用户名、密码、Emby API 敏感信息删除
>
> 可以复制上面的配置，使用类似在线 json 格式化的工具进行一次处理，方便阅读，[JSON 在线解析及格式化验证 - JSON.cn](https://www.json.cn/#)

```json
{
  "user_info": {
    "username": "xx", // 这里是用户名，需要替换掉
    "password": "xx" // 这里是密码，需要替换掉
  },
  "common_settings": {
    "scan_interval": "6h",
    "threads": 1,
    "run_scan_at_start_up": false,
    "movie_paths": ["X:\\电影"],
    "series_paths": ["X:\\连续剧"]
  },
  "advanced_settings": {
    "proxy_settings": {
      "use_http_proxy": false,
      "http_proxy_address": ""
    },
    "debug_mode": false,
    "save_full_season_tmp_subtitles": true,
    "sub_type_priority": 0,
    "sub_name_formatter": 0,
    "save_multi_sub": true,
    "custom_video_exts": [],
    "fix_time_line": false,
    "topic": 1
  },
  "emby_settings": {
    "enable": true,
    "address_url": "http://192.168.50.xxx:xxx", // 这里替换掉
    "api_key": "xxxxxxxxxxxxxx", // 这里替换掉
    "max_request_video_number": 100,
    "skip_watched": true,
    "movie_paths_mapping": {
      "X:\\电影": "/mnt/share1/电影"
    },
    "series_paths_mapping": {
      "X:\\连续剧": "/mnt/share1/连续剧"
    }
  },
  "developer_settings": {
    "enable": false,
    "bark_server_address": ""
  },
  "timeline_fixer_settings": {
    "max_offset_time": 120,
    "min_offset": 0.1
  }
}
```

## 如果是使用 Docker，请给出对应的配置信息

> 比如 Docker-Compose 信息，如果是其他方式使用忽略

```
  chinesesubfinder:
    container_name: chinesesubfinder
    image: allanpk716/chinesesubfinder:latest
    volumes:
      - /usr/appdata/chinesesubfinder/config:/config 
      - /usr/appdata/chinesesubfinder/browser:/root/.cache/rod/browser   
      - /storage:/media    
    environment:
      - PUID=1000      
      - PGID=1000     
      - PERMS=true     
      - TZ=Asia/Shanghai 
      - UMASK=022        
    ports:
      - "127.0.0.1:17830:19035"
      - "127.0.0.1:17831:19037"
    restart: always
    network_mode: bridge
    hostname: chinesesubfinder
    logging:
        driver: "json-file"
        options:
          max-size: "100m"
```
## 给出媒体文件夹的目录结构

> 首先你需要去看主页的部署教程，确认你目录结构是规范的，如果你觉得没问题，那么请除非目录结构截图

> 是否看过对应的目录结构要求文档？
是
- [电影的推荐目录结构](https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E7%94%B5%E5%BD%B1%E5%92%8C%E8%BF%9E%E7%BB%AD%E5%89%A7%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84%E7%A4%BA%E4%BE%8B.md)
- [连续剧目录结构要求](https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E8%BF%9E%E7%BB%AD%E5%89%A7%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84%E8%A6%81%E6%B1%82.md)

## 请给出当次问题的完整日志

> 日志在程序的 Logs 目录下，如果你用的是 docker ，那么需要你映射出来。

> /volume1/docker/chinesesubfinder/config:/config 下，Logs 中
 没有产生日志 无日志, 只有docker 运行日志 
```
Attaching to chinesesubfinder
chinesesubfinder  | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
chinesesubfinder  | [s6-init] ensuring user provided files have correct perms...exited 0.
chinesesubfinder  | [fix-attrs.d] applying ownership & permissions fixes...
chinesesubfinder  | [fix-attrs.d] done.
chinesesubfinder  | [cont-init.d] executing container initialization scripts...
chinesesubfinder  | [cont-init.d] 10-fixuser: executing...
chinesesubfinder  | 已设置 PERMS=true，重设 '/media' 目录权限为 1000:1000 所有...
chinesesubfinder  | [cont-init.d] 10-fixuser: exited 0.
chinesesubfinder  | [cont-init.d] done.
chinesesubfinder  | [services.d] starting services
chinesesubfinder  | [services.d] done.
chinesesubfinder  | fatal error: unexpected signal during runtime execution
chinesesubfinder  | [signal SIGSEGV: segmentation violation code=0x2 addr=0x7f487d049072 pc=0x7f486fe68a7f]
chinesesubfinder  |
chinesesubfinder  | runtime stack:
chinesesubfinder  | runtime.throw({0x12a12b0, 0x19b36b6})
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/runtime/panic.go:1198 +0x71
chinesesubfinder  | runtime.sigpanic()
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/runtime/signal_unix.go:719 +0x389
chinesesubfinder  |
chinesesubfinder  | goroutine 8 [syscall]:
chinesesubfinder  | runtime.cgocall(0xe4e4e0, 0xc00004e590)
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/runtime/cgocall.go:156 +0x5c fp=0xc00004e568 sp=0xc00004e530 pc=0x405fdc
chinesesubfinder  | net._C2func_getaddrinfo(0xc0002b4500, 0x0, 0xc0002a1350, 0xc000010908)
chinesesubfinder  |     _cgo_gotypes.go:91 +0x56 fp=0xc00004e590 sp=0xc00004e568 pc=0x5c7ed6
chinesesubfinder  | net.cgoLookupIPCNAME.func1({0xc0002b4500, 0x0, 0x0}, 0xc0002b44a0, 0xc00004e650)
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/cgo_unix.go:163 +0x9f fp=0xc00004e5e8 sp=0xc00004e590 pc=0x5c9c1f
chinesesubfinder  | net.cgoLookupIPCNAME({0x12505e9, 0x3}, {0xc0002b44a0, 0x5})
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/cgo_unix.go:163 +0x16d fp=0xc00004e738 sp=0xc00004e5e8 pc=0x5c946d
chinesesubfinder  | net.cgoIPLookup(0x263ee90, {0x12505e9, 0xc0002b44c0}, {0xc0002b44a0, 0xc0000b8420})
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/cgo_unix.go:220 +0x3b fp=0xc00004e7a8 sp=0xc00004e738 pc=0x5c9cdb
chinesesubfinder  | net.cgoLookupIP·dwrap·25()
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/cgo_unix.go:230 +0x36 fp=0xc00004e7e0 sp=0xc00004e7a8 pc=0x5ca156
chinesesubfinder  | runtime.goexit()
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00004e7e8 sp=0xc00004e7e0 pc=0x46b9c1
chinesesubfinder  | created by net.cgoLookupIP
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/cgo_unix.go:230 +0x125
chinesesubfinder  |
chinesesubfinder  | goroutine 1 [select, locked to thread]:
chinesesubfinder  | net/http.(*Transport).getConn(0xc0002c0140, 0xc000221240, {{}, 0x0, {0xc00007c6c0, 0x5}, {0xc0002b44a0, 0x1d}, 0x0})
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/http/transport.go:1372 +0x5d2
chinesesubfinder  | net/http.(*Transport).roundTrip(0xc0002c0140, 0xc0000e6600)
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/http/transport.go:581 +0x774
chinesesubfinder  | net/http.(*Transport).RoundTrip(0x30, 0x18a25c0)
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/http/roundtrip.go:18 +0x19
chinesesubfinder  | net/http.send(0xc0000e6600, {0x18a25c0, 0xc0002c0140}, {0x12241e0, 0x1, 0x0})
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/http/client.go:252 +0x5d8
chinesesubfinder  | net/http.(*Client).send(0xc0002a0e40, 0xc0000e6600, {0xc0000e6600, 0x2f, 0x0})
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/http/client.go:176 +0x9b
chinesesubfinder  | net/http.(*Client).do(0xc0002a0e40, 0xc0000e6600)
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/http/client.go:725 +0x908
chinesesubfinder  | net/http.(*Client).Do(...)
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/http/client.go:593
chinesesubfinder  | github.com/EDDYCJY/fake-useragent/downloader.(*Download).Get(0xc000107528, {0xc00007c6c0, 0x60})
chinesesubfinder  |     /home/runner/go/pkg/mod/github.com/!e!d!d!y!c!j!y/fake-useragent@v0.2.0/downloader/http.go:37 +0x188
chinesesubfinder  | github.com/EDDYCJY/fake-useragent/useragent/cache.(*raw).Get(0x12835cc)
chinesesubfinder  |     /home/runner/go/pkg/mod/github.com/!e!d!d!y!c!j!y/fake-useragent@v0.2.0/useragent/cache/rawgithub.go:32 +0x45
chinesesubfinder  | github.com/allanpk716/fake-useragent.(*browser).load(0xc0002b4400)
chinesesubfinder  |     /home/runner/go/pkg/mod/github.com/allanpk716/fake-useragent@v0.2.1/b.go:77 +0x2c6
chinesesubfinder  | github.com/allanpk716/fake-useragent.NewBrowser({0xc0001076e8, 0x20adce8, 0x12b0d3f}, {0x4a})
chinesesubfinder  |     /home/runner/go/pkg/mod/github.com/allanpk716/fake-useragent@v0.2.1/b.go:51 +0x90
chinesesubfinder  | github.com/allanpk716/fake-useragent.init()
chinesesubfinder  |     /home/runner/go/pkg/mod/github.com/allanpk716/fake-useragent@v0.2.1/b.go:30 +0x2f
chinesesubfinder  |
chinesesubfinder  | goroutine 6 [select]:
chinesesubfinder  | net.(*Resolver).lookupIPAddr(0x263ee80, {0x18b9210, 0xc000070ae0}, {0x12505e9, 0xc0001ab630}, {0xc0002b44a0, 0x19})
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/lookup.go:302 +0x5c7
chinesesubfinder  | net.(*Resolver).internetAddrList(0x18b9210, {0x18b9210, 0xc000070ae0}, {0x12505e9, 0x3}, {0xc0002b44a0, 0x1d})
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/ipsock.go:288 +0x67a
chinesesubfinder  | net.(*Resolver).resolveAddrList(0x267d4e8, {0x18b9210, 0xc000070ae0}, {0x1251ebb, 0x4}, {0x12505e9, 0x20a66b8}, {0xc0002b44a0, 0x1d}, {0x0, ...})
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/dial.go:221 +0x41b
chinesesubfinder  | net.(*Dialer).DialContext(0xc0000708a0, {0x18b91d8, 0xc0000360a0}, {0x12505e9, 0x7f487d85ce38}, {0xc0002b44a0, 0x118})
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/dial.go:406 +0x448
chinesesubfinder  | net/http.(*Transport).dial(0x40, {0x18b91d8, 0xc0000360a0}, {0x12505e9, 0x7f48a4e476c0}, {0xc0002b44a0, 0x38})
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/http/transport.go:1166 +0xda
chinesesubfinder  | net/http.(*Transport).dialConn(0xc0002c0140, {0x18b91d8, 0xc0000360a0}, {{}, 0x0, {0xc00007c6c0, 0x5}, {0xc0002b44a0, 0x1d}, 0x0})
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/http/transport.go:1604 +0x845
chinesesubfinder  | net/http.(*Transport).dialConnFor(0x0, 0xc0000b8420)
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/http/transport.go:1446 +0xb0
chinesesubfinder  | created by net/http.(*Transport).queueForDial
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/http/transport.go:1415 +0x3d7
chinesesubfinder  |
chinesesubfinder  | goroutine 7 [select]:
chinesesubfinder  | net.cgoLookupIP({0x18b91a0, 0xc0002212c0}, {0x12505e9, 0x19}, {0xc0002b44a0, 0x0})
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/cgo_unix.go:231 +0x1b7
chinesesubfinder  | net.(*Resolver).lookupIP(0x263ee80, {0x18b91a0, 0xc0002212c0}, {0x12505e9, 0x3}, {0xc0002b44a0, 0x19})
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/lookup_unix.go:97 +0x128
chinesesubfinder  | net.glob..func1({0x18b91a0, 0xc0002212c0}, 0x0, {0x12505e9, 0x0}, {0xc0002b44a0, 0x6c5fb0})
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/hook.go:23 +0x3d
chinesesubfinder  | net.(*Resolver).lookupIPAddr.func1()
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/lookup.go:296 +0x9f
chinesesubfinder  | internal/singleflight.(*Group).doCall(0x263ee90, 0xc0001ab680, {0xc0002b44c0, 0x1d}, 0xc0000b8420)
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/internal/singleflight/singleflight.go:95 +0x3b
chinesesubfinder  | created by internal/singleflight.(*Group).DoChan
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/internal/singleflight/singleflight.go:88 +0x2f1
chinesesubfinder  | fatal error: unexpected signal during runtime execution
chinesesubfinder  | [signal SIGSEGV: segmentation violation code=0x2 addr=0x7f9219306072 pc=0x7f9218161a7f]
chinesesubfinder  |
chinesesubfinder  | runtime stack:
chinesesubfinder  | runtime.throw({0x12a12b0, 0x19b36b6})
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/runtime/panic.go:1198 +0x71
chinesesubfinder  | runtime.sigpanic()
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/runtime/signal_unix.go:719 +0x389
chinesesubfinder  |
chinesesubfinder  | goroutine 8 [syscall]:
chinesesubfinder  | runtime.cgocall(0xe4e4e0, 0xc00004e590)
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/runtime/cgocall.go:156 +0x5c fp=0xc00004e568 sp=0xc00004e530 pc=0x405fdc
chinesesubfinder  | net._C2func_getaddrinfo(0xc0002b4500, 0x0, 0xc0002a1350, 0xc000010900)
chinesesubfinder  |     _cgo_gotypes.go:91 +0x56 fp=0xc00004e590 sp=0xc00004e568 pc=0x5c7ed6
chinesesubfinder  | net.cgoLookupIPCNAME.func1({0xc0002b4500, 0x0, 0x0}, 0xc0002b44a0, 0xc00004e650)
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/cgo_unix.go:163 +0x9f fp=0xc00004e5e8 sp=0xc00004e590 pc=0x5c9c1f
chinesesubfinder  | net.cgoLookupIPCNAME({0x12505e9, 0x3}, {0xc0002b44a0, 0x5})
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/cgo_unix.go:163 +0x16d fp=0xc00004e738 sp=0xc00004e5e8 pc=0x5c946d
chinesesubfinder  | net.cgoIPLookup(0x263ee90, {0x12505e9, 0xc0002b44c0}, {0xc0002b44a0, 0xc0000b8420})
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/cgo_unix.go:220 +0x3b fp=0xc00004e7a8 sp=0xc00004e738 pc=0x5c9cdb
chinesesubfinder  | net.cgoLookupIP·dwrap·25()
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/cgo_unix.go:230 +0x36 fp=0xc00004e7e0 sp=0xc00004e7a8 pc=0x5ca156
chinesesubfinder  | runtime.goexit()
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00004e7e8 sp=0xc00004e7e0 pc=0x46b9c1
chinesesubfinder  | created by net.cgoLookupIP
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/cgo_unix.go:230 +0x125
chinesesubfinder  |
chinesesubfinder  | goroutine 1 [select, locked to thread]:
chinesesubfinder  | net/http.(*Transport).getConn(0xc0002c0140, 0xc000223240, {{}, 0x0, {0xc00007c6c0, 0x5}, {0xc0002b44a0, 0x1d}, 0x0})
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/http/transport.go:1372 +0x5d2
chinesesubfinder  | net/http.(*Transport).roundTrip(0xc0002c0140, 0xc0000e6600)
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/http/transport.go:581 +0x774
chinesesubfinder  | net/http.(*Transport).RoundTrip(0x30, 0x18a25c0)
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/http/roundtrip.go:18 +0x19
chinesesubfinder  | net/http.send(0xc0000e6600, {0x18a25c0, 0xc0002c0140}, {0x12241e0, 0x1, 0x0})
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/http/client.go:252 +0x5d8
chinesesubfinder  | net/http.(*Client).send(0xc0002a0e40, 0xc0000e6600, {0xc0000e6600, 0x2f, 0x0})
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/http/client.go:176 +0x9b
chinesesubfinder  | net/http.(*Client).do(0xc0002a0e40, 0xc0000e6600)
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/http/client.go:725 +0x908
chinesesubfinder  | net/http.(*Client).Do(...)
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/http/client.go:593
chinesesubfinder  | github.com/EDDYCJY/fake-useragent/downloader.(*Download).Get(0xc000107528, {0xc00007c6c0, 0x60})
chinesesubfinder  |     /home/runner/go/pkg/mod/github.com/!e!d!d!y!c!j!y/fake-useragent@v0.2.0/downloader/http.go:37 +0x188
chinesesubfinder  | github.com/EDDYCJY/fake-useragent/useragent/cache.(*raw).Get(0x12835cc)
chinesesubfinder  |     /home/runner/go/pkg/mod/github.com/!e!d!d!y!c!j!y/fake-useragent@v0.2.0/useragent/cache/rawgithub.go:32 +0x45
chinesesubfinder  | github.com/allanpk716/fake-useragent.(*browser).load(0xc0002b4400)
chinesesubfinder  |     /home/runner/go/pkg/mod/github.com/allanpk716/fake-useragent@v0.2.1/b.go:77 +0x2c6
chinesesubfinder  | github.com/allanpk716/fake-useragent.NewBrowser({0xc0001076e8, 0x20adce8, 0x12b0d3f}, {0x4a})
chinesesubfinder  |     /home/runner/go/pkg/mod/github.com/allanpk716/fake-useragent@v0.2.1/b.go:51 +0x90
chinesesubfinder  | github.com/allanpk716/fake-useragent.init()
chinesesubfinder  |     /home/runner/go/pkg/mod/github.com/allanpk716/fake-useragent@v0.2.1/b.go:30 +0x2f
chinesesubfinder  |
chinesesubfinder  | goroutine 6 [select]:
chinesesubfinder  | net.(*Resolver).lookupIPAddr(0x263ee80, {0x18b9210, 0xc000070ae0}, {0x12505e9, 0xc0001ab630}, {0xc0002b44a0, 0x19})
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/lookup.go:302 +0x5c7
chinesesubfinder  | net.(*Resolver).internetAddrList(0x18b9210, {0x18b9210, 0xc000070ae0}, {0x12505e9, 0x3}, {0xc0002b44a0, 0x1d})
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/ipsock.go:288 +0x67a
chinesesubfinder  | net.(*Resolver).resolveAddrList(0x267d4e8, {0x18b9210, 0xc000070ae0}, {0x1251ebb, 0x4}, {0x12505e9, 0x20a66b8}, {0xc0002b44a0, 0x1d}, {0x0, ...})
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/dial.go:221 +0x41b
chinesesubfinder  | net.(*Dialer).DialContext(0xc0000708a0, {0x18b91d8, 0xc0000360a0}, {0x12505e9, 0x7f9219b1a1f0}, {0xc0002b44a0, 0x118})
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/dial.go:406 +0x448
chinesesubfinder  | net/http.(*Transport).dial(0x40, {0x18b91d8, 0xc0000360a0}, {0x12505e9, 0x7f92411046c0}, {0xc0002b44a0, 0x38})
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/http/transport.go:1166 +0xda
chinesesubfinder  | net/http.(*Transport).dialConn(0xc0002c0140, {0x18b91d8, 0xc0000360a0}, {{}, 0x0, {0xc00007c6c0, 0x5}, {0xc0002b44a0, 0x1d}, 0x0})
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/http/transport.go:1604 +0x845
chinesesubfinder  | net/http.(*Transport).dialConnFor(0x0, 0xc0000b8420)
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/http/transport.go:1446 +0xb0
chinesesubfinder  | created by net/http.(*Transport).queueForDial
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/http/transport.go:1415 +0x3d7
chinesesubfinder  |
chinesesubfinder  | goroutine 7 [select]:
chinesesubfinder  | net.cgoLookupIP({0x18b91a0, 0xc0002232c0}, {0x12505e9, 0x19}, {0xc0002b44a0, 0x0})
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/cgo_unix.go:231 +0x1b7
chinesesubfinder  | net.(*Resolver).lookupIP(0x263ee80, {0x18b91a0, 0xc0002232c0}, {0x12505e9, 0x3}, {0xc0002b44a0, 0x19})
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/lookup_unix.go:97 +0x128
chinesesubfinder  | net.glob..func1({0x18b91a0, 0xc0002232c0}, 0x0, {0x12505e9, 0x0}, {0xc0002b44a0, 0x6c5fb0})
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/hook.go:23 +0x3d
chinesesubfinder  | net.(*Resolver).lookupIPAddr.func1()
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/lookup.go:296 +0x9f
chinesesubfinder  | internal/singleflight.(*Group).doCall(0x263ee90, 0xc0001ab680, {0xc0002b44c0, 0x1d}, 0xc0000b8420)
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/internal/singleflight/singleflight.go:95 +0x3b
chinesesubfinder  | created by internal/singleflight.(*Group).DoChan
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/internal/singleflight/singleflight.go:88 +0x2f1
chinesesubfinder  | fatal error: unexpected signal during runtime execution
chinesesubfinder  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x63 pc=0x7fb9baee1ef4]
chinesesubfinder  |
chinesesubfinder  | runtime stack:
chinesesubfinder  | runtime.throw({0x12a12b0, 0x0})
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/runtime/panic.go:1198 +0x71
chinesesubfinder  | runtime.sigpanic()
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/runtime/signal_unix.go:719 +0x389
chinesesubfinder  |
chinesesubfinder  | goroutine 8 [syscall]:
chinesesubfinder  | runtime.cgocall(0xe4e4e0, 0xc00004e590)
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/runtime/cgocall.go:156 +0x5c fp=0xc00004e568 sp=0xc00004e530 pc=0x405fdc
chinesesubfinder  | net._C2func_getaddrinfo(0xc0002b4500, 0x0, 0xc0002a1350, 0xc000010900)
chinesesubfinder  |     _cgo_gotypes.go:91 +0x56 fp=0xc00004e590 sp=0xc00004e568 pc=0x5c7ed6
chinesesubfinder  | net.cgoLookupIPCNAME.func1({0xc0002b4500, 0x0, 0x0}, 0xc0002b44a0, 0xc00004e650)
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/cgo_unix.go:163 +0x9f fp=0xc00004e5e8 sp=0xc00004e590 pc=0x5c9c1f
chinesesubfinder  | net.cgoLookupIPCNAME({0x12505e9, 0x3}, {0xc0002b44a0, 0x5})
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/cgo_unix.go:163 +0x16d fp=0xc00004e738 sp=0xc00004e5e8 pc=0x5c946d
chinesesubfinder  | net.cgoIPLookup(0x263ee90, {0x12505e9, 0xc0002b44c0}, {0xc0002b44a0, 0xc0000b8420})
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/cgo_unix.go:220 +0x3b fp=0xc00004e7a8 sp=0xc00004e738 pc=0x5c9cdb
chinesesubfinder  | net.cgoLookupIP·dwrap·25()
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/cgo_unix.go:230 +0x36 fp=0xc00004e7e0 sp=0xc00004e7a8 pc=0x5ca156
chinesesubfinder  | runtime.goexit()
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00004e7e8 sp=0xc00004e7e0 pc=0x46b9c1
chinesesubfinder  | created by net.cgoLookupIP
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/cgo_unix.go:230 +0x125
chinesesubfinder  |
chinesesubfinder  | goroutine 1 [select, locked to thread]:
chinesesubfinder  | net/http.(*Transport).getConn(0xc0002c0140, 0xc000223240, {{}, 0x0, {0xc00007c6c0, 0x5}, {0xc0002b44a0, 0x1d}, 0x0})
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/http/transport.go:1372 +0x5d2
chinesesubfinder  | net/http.(*Transport).roundTrip(0xc0002c0140, 0xc0000e6600)
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/http/transport.go:581 +0x774
chinesesubfinder  | net/http.(*Transport).RoundTrip(0x30, 0x18a25c0)
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/http/roundtrip.go:18 +0x19
chinesesubfinder  | net/http.send(0xc0000e6600, {0x18a25c0, 0xc0002c0140}, {0x12241e0, 0x1, 0x0})
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/http/client.go:252 +0x5d8
chinesesubfinder  | net/http.(*Client).send(0xc0002a0e40, 0xc0000e6600, {0xc0000e6600, 0x2f, 0x0})
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/http/client.go:176 +0x9b
chinesesubfinder  | net/http.(*Client).do(0xc0002a0e40, 0xc0000e6600)
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/http/client.go:725 +0x908
chinesesubfinder  | net/http.(*Client).Do(...)
chinesesubfinder  |     /opt/hostedtoolcache/go/1.17.13/x64/src/net/http/client.go:593
chinesesubfinder  | github.com/EDDYCJY/fake-useragent/downloader.(*Download).Get(0xc000107528, {0xc00007c6c0, 0x60})
chinesesubfinder  |     /home/runner/go/pkg/mod/github.com/!e!d!d!y!c!j!y/fake-useragent@v0.2.0/downloader/http.go:37 +0x188
chinesesubfinder  | github.com/EDDYCJY/fake-useragent/useragent/cache.(*raw).Get(0x12835cc)
chinesesubfinder  |     /home/runner/go/pkg/mod/github.com/!e!d!d!y!c!j!y/fake-useragent@v0.2.0/useragent/cache/rawgithub.go:32 +0x45
chinesesubfinder  | github.com/allanpk716/fake-useragent.(*browser).load(0xc0002b4400)
chinesesubfinder  |     /home/runner/go/pkg/mod/github.com/allanpk716/fake-useragent@v0.2.1/b.go:77 +0x2c6
chinesesubfinder  | github.com/allanpk716/fake-useragent.NewBrowser({0xc0001076e8, 0x20adce8, 0x12b0d3f}, {0x4a})
chinesesubfinder  |     /home/runner/go/pkg/mod/github.com/allanpk716/fake-useragent@v0.2.1/b.go:51 +0x90
chinesesubfinder  | github.com/allanpk716/fake-useragent.init()
chinesesubfinder  |     /home/runner/go/pkg/mod/github.com/allanpk716/fake-useragent@v0.2.1/b.go:30 +0x2f
chinesesubfinder  |
后面就是循环重复了 
```

**Comment by allanpk716** [comment]
你试试 lite 版本的镜像，估计是不支持 Chrome
