### ISSUE TITLE
无法开始下载字幕 [ERROR]: 2022-10-09 21:46:14 - Downloader.QueueDownloader() panic

### ISSUE THREAD

**Issue by Egan-middle** [allanpk716/ChineseSubFinder#507]
> chinesesubfinder 版本: v4.1
> 环境: Window 10

> 无法开始下载字幕，是什么问题？之前使用一直没有问题，多谢

控制台出现：
[ERROR]: 2022-10-09 21:46:14 - Downloader.QueueDownloader() panic
[ERROR]: 2022-10-09 21:46:14 - goroutine 11235 [running]:
github.com/allanpk716/ChineseSubFinder/pkg/my_util.PrintPanicStack(0xc000174230)
        /home/runner/work/ChineseSubFinder/ChineseSubFinder/pkg/my_util/util.go:859 +0x3d
github.com/allanpk716/ChineseSubFinder/pkg/downloader.(*Downloader).queueDownloaderLocal.func1()
        /home/runner/work/ChineseSubFinder/ChineseSubFinder/pkg/downloader/queue_local.go:25 +0x7c
panic({0x1763060, 0x1612c60})
        /opt/hostedtoolcache/go/1.17.13/x64/src/runtime/panic.go:1047 +0x266
github.com/allanpk716/ChineseSubFinder/pkg/logic/sub_supplier.(*SubSupplierHub).SeriesNeedDlSub(0xc00042b170, {0xc000884f80, 0x3d}, 0x70, 0xb1)
        /home/runner/work/ChineseSubFinder/ChineseSubFinder/pkg/logic/sub_supplier/subSupplierHub.go:95 +0x3f
github.com/allanpk716/ChineseSubFinder/pkg/downloader.(*Downloader).queueDownloaderLocal(0xc0001fc140)
        /home/runner/work/ChineseSubFinder/ChineseSubFinder/pkg/downloader/queue_local.go:164 +0xc50
github.com/allanpk716/ChineseSubFinder/pkg/downloader.(*Downloader).QueueDownloader(0xc0001fc140)
        /home/runner/work/ChineseSubFinder/ChineseSubFinder/pkg/downloader/downloader.go:177 +0x1e
github.com/robfig/cron/v3.FuncJob.Run(0x4)
        /home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/cron.go:131 +0x1a
github.com/robfig/cron/v3.DelayIfStillRunning.func1.1()
        /home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/chain.go:71 +0x1aa
github.com/robfig/cron/v3.FuncJob.Run(0xc000753fd0)
        /home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/cron.go:131 +0x1a
github.com/robfig/cron/v3.(*Cron).startJob.func1()
        /home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/cron.go:307 +0x6a
created by github.com/robfig/cron/v3.(*Cron).startJob
        /home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/cron.go:305 +0xb2

> 能够重现

**Comment by Egan-middle** [comment]
后面好了，可以下了
