### ISSUE TITLE
0.17.1版docker环境下无法正常使用，

### ISSUE THREAD

**Issue by hsj1992** [allanpk716/ChineseSubFinder#63]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.17.1

环境: docker

## 你遇到什么问题了？

软件没有工作，从Log看一启动就遭遇Error。

## 你的问题能够重现嘛？

能够重现，一启动就在一直重复发生。

## 你期望的结果

难道是我docker的变量参数配置有问题？
希望能发现是啥问题，能正常使用。

## 可以提供遇到问题时候，电影、连续剧的信息吗？

就正常的媒体库，emby和jellyfin里都正常使用，利用TMM刮削和重命名过。

## 出错的日志信息可以复制一些出来吗？

日志在程序的 Logs 目录下，如果你用的是 docker ，那么需要你映射出来。

````

[INFO]: 2021-09-26 22:22:34 - UseProxy: http://192.168.31.3:7890

[INFO]: 2021-09-26 22:22:34 - ProxyTest Target Site http://google.com Speed: 229 Status: 200

[INFO]: 2021-09-26 22:22:34 - MovieFolder: /media/movie

[INFO]: 2021-09-26 22:22:34 - SeriesFolder: /media/tv

[INFO]: 2021-09-26 22:22:34 - HotFix Start...

[INFO]: 2021-09-26 22:22:34 - HotFix End

[INFO]: 2021-09-26 22:22:34 - Change Sub Name Format Start...



2021/09/26 22:22:34 /homelab/buildspace/internal/pkg/sub_formatter/sub_format_changer.go:179 record not found

[0.208ms] [rows:0] SELECT * FROM `sub_format_recs` WHERE `sub_format_recs`.`deleted_at` IS NULL ORDER BY `sub_format_recs`.`id` LIMIT 1

panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x8ce8fd]


goroutine 1 [running]:

github.com/allanpk716/ChineseSubFinder/internal/pkg/sub_parser_hub.SubParserHub.DetermineFileTypeFromFile({{0xc0000c69e0, 0xc000659830, 0xc0006598a9}}, {0xc000659830, 0x0})

	/homelab/buildspace/internal/pkg/sub_parser_hub/subParserHub.go:44 +0x15d

github.com/allanpk716/ChineseSubFinder/internal/pkg/sub_formatter/normal.Formatter.IsMatchThisFormat({0x40f156}, {0xc000659830, 0x81})

	/homelab/buildspace/internal/pkg/sub_formatter/normal/normal.go:65 +0x10b

github.com/allanpk716/ChineseSubFinder/internal/pkg/sub_formatter.SubFormatChanger.autoDetectAndChange({{0xc000424710, 0xc}, {0xc000424790, 0x9}, 0xc0003d8e70}, 0xc0002cb9d8, {0xc000659830, 0x81}, 0x0)

	/homelab/buildspace/internal/pkg/sub_formatter/sub_format_changer.go:98 +0xfa

github.com/allanpk716/ChineseSubFinder/internal/pkg/sub_formatter.SubFormatChanger.AutoDetectThenChangeTo({{0xc000424710, 0xc}, {0xc000424790, 0x9}, 0xc0003d8e70}, 0x0)

	/homelab/buildspace/internal/pkg/sub_formatter/sub_format_changer.go:87 +0x3b6

github.com/allanpk716/ChineseSubFinder/internal/pkg/sub_formatter.SubFormatChangerProcess({0xc000424710, 0xc}, {0xc000424790, 0x9}, 0x0)

	/homelab/buildspace/internal/pkg/sub_formatter/sub_format_changer.go:184 +0x270

main.main()

	/homelab/buildspace/cmd/chinesesubfinder/main.go:94 +0x54a

(EE) 

Fatal server error:

(EE) Server is already active for display 99

	If this server is no longer running, remove /tmp/.X99-lock

	and start again.

(EE) 

[INFO]: 2021-09-26 22:22:35 - ChineseSubFinder Version: v0.17.1

[INFO]: 2021-09-26 22:22:35 - UseProxy: http://192.168.31.3:7890

[INFO]: 2021-09-26 22:22:36 - ProxyTest Target Site http://google.com Speed: 241 Status: 200

[INFO]: 2021-09-26 22:22:36 - MovieFolder: /media/movie

[INFO]: 2021-09-26 22:22:36 - SeriesFolder: /media/tv

[INFO]: 2021-09-26 22:22:36 - HotFix Start...

[INFO]: 2021-09-26 22:22:36 - HotFix End

[INFO]: 2021-09-26 22:22:36 - Change Sub Name Format Start...



2021/09/26 22:22:36 /homelab/buildspace/internal/pkg/sub_formatter/sub_format_changer.go:179 record not found

[0.237ms] [rows:0] SELECT * FROM `sub_format_recs` WHERE `sub_format_recs`.`deleted_at` IS NULL ORDER BY `sub_format_recs`.`id` LIMIT 1

panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x8ce8fd]


goroutine 1 [running]:

github.com/allanpk716/ChineseSubFinder/internal/pkg/sub_parser_hub.SubParserHub.DetermineFileTypeFromFile({{0xc0004a97c0, 0xc0001bb830, 0xc0001bb8a9}}, {0xc0001bb830, 0x0})

	/homelab/buildspace/internal/pkg/sub_parser_hub/subParserHub.go:44 +0x15d

github.com/allanpk716/ChineseSubFinder/internal/pkg/sub_formatter/normal.Formatter.IsMatchThisFormat({0x40f156}, {0xc0001bb830, 0x81})

	/homelab/buildspace/internal/pkg/sub_formatter/normal/normal.go:65 +0x10b

github.com/allanpk716/ChineseSubFinder/internal/pkg/sub_formatter.SubFormatChanger.autoDetectAndChange({{0xc000034790, 0xc}, {0xc0000347c0, 0x9}, 0xc0004cbe90}, 0xc0002c59d8, {0xc0001bb830, 0x81}, 0x0)

	/homelab/buildspace/internal/pkg/sub_formatter/sub_format_changer.go:98 +0xfa

github.com/allanpk716/ChineseSubFinder/internal/pkg/sub_formatter.SubFormatChanger.AutoDetectThenChangeTo({{0xc000034790, 0xc}, {0xc0000347c0, 0x9}, 0xc0004cbe90}, 0x0)

	/homelab/buildspace/internal/pkg/sub_formatter/sub_format_changer.go:87 +0x3b6

github.com/allanpk716/ChineseSubFinder/internal/pkg/sub_formatter.SubFormatChangerProcess({0xc000034790, 0xc}, {0xc0000347c0, 0x9}, 0x0)

	/homelab/buildspace/internal/pkg/sub_formatter/sub_format_changer.go:184 +0x270

main.main()

	/homelab/buildspace/cmd/chinesesubfinder/main.go:94 +0x54a

(EE) 

Fatal server error:

(EE) Server is already active for display 99

	If this server is no longer running, remove /tmp/.X99-lock

	and start again.

(EE) 

[INFO]: 2021-09-26 22:22:37 - ChineseSubFinder Version: v0.17.1

[INFO]: 2021-09-26 22:22:37 - UseProxy: http://192.168.31.3:7890

[INFO]: 2021-09-26 22:22:38 - ProxyTest Target Site http://google.com Speed: 1253 Status: 200

[INFO]: 2021-09-26 22:22:38 - MovieFolder: /media/movie

[INFO]: 2021-09-26 22:22:38 - SeriesFolder: /media/tv

[INFO]: 2021-09-26 22:22:38 - HotFix Start...

[INFO]: 2021-09-26 22:22:38 - HotFix End

[INFO]: 2021-09-26 22:22:38 - Change Sub Name Format Start...



2021/09/26 22:22:38 /homelab/buildspace/internal/pkg/sub_formatter/sub_format_changer.go:179 record not found

[0.213ms] [rows:0] SELECT * FROM `sub_format_recs` WHERE `sub_format_recs`.`deleted_at` IS NULL ORDER BY `sub_format_recs`.`id` LIMIT 1

panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x8ce8fd]


goroutine 1 [running]:

github.com/allanpk716/ChineseSubFinder/internal/pkg/sub_parser_hub.SubParserHub.DetermineFileTypeFromFile({{0xc00057c080, 0xc000417830, 0xc0004178a9}}, {0xc000417830, 0x0})

	/homelab/buildspace/internal/pkg/sub_parser_hub/subParserHub.go:44 +0x15d

github.com/allanpk716/ChineseSubFinder/internal/pkg/sub_formatter/normal.Formatter.IsMatchThisFormat({0x40f156}, {0xc000417830, 0x81})

	/homelab/buildspace/internal/pkg/sub_formatter/normal/normal.go:65 +0x10b

github.com/allanpk716/ChineseSubFinder/internal/pkg/sub_formatter.SubFormatChanger.autoDetectAndChange({{0xc0000346d0, 0xc}, {0xc000034700, 0x9}, 0xc00057a900}, 0xc0004d39d8, {0xc000417830, 0x81}, 0x0)

	/homelab/buildspace/internal/pkg/sub_formatter/sub_format_changer.go:98 +0xfa

github.com/allanpk716/ChineseSubFinder/internal/pkg/sub_formatter.SubFormatChanger.AutoDetectThenChangeTo({{0xc0000346d0, 0xc}, {0xc000034700, 0x9}, 0xc00057a900}, 0x0)

	/homelab/buildspace/internal/pkg/sub_formatter/sub_format_changer.go:87 +0x3b6

github.com/allanpk716/ChineseSubFinder/internal/pkg/sub_formatter.SubFormatChangerProcess({0xc0000346d0, 0xc}, {0xc000034700, 0x9}, 0x0)

	/homelab/buildspace/internal/pkg/sub_formatter/sub_format_changer.go:184 +0x270

main.main()

	/homelab/buildspace/cmd/chinesesubfinder/main.go:94 +0x54a

(EE) 

Fatal server error:

(EE) Server is already active for display 99

	If this server is no longer running, remove /tmp/.X99-lock

	and start again.

(EE) 

[INFO]: 2021-09-26 22:22:39 - ChineseSubFinder Version: v0.17.1

[INFO]: 2021-09-26 22:22:39 - UseProxy: http://192.168.31.3:7890
````

**Comment by allanpk716** [comment]
已推送修复 v0.17.2
